// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentIdentity {
    /// Identifies the client that owns the business consequences of this payment.
    #[prost(string, tag = "1")]
    pub payment_client: ::prost::alloc::string::String,
    /// Client-provided idempotency key for one logical payment attempt.
    #[prost(string, tag = "2")]
    pub payment_idempotency_key: ::prost::alloc::string::String,
}
/// Completes a payment on behalf of a payment client. client_payment_reference
/// remains opaque to the payment service and is returned in payment outcome events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletePaymentRequest {
    #[prost(message, optional, tag = "1")]
    pub payment: ::core::option::Option<PaymentIdentity>,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    #[prost(string, tag = "3")]
    pub client_payment_reference: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub amount_cents: u64,
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::charge::v1::ChargeMethod", tag = "6")]
    pub charge_method: i32,
    #[prost(string, optional, tag = "7")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub invoice_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub invoice_guid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "10")]
    pub payment_config: ::core::option::Option<
        super::super::super::common::v1::PaymentConfig,
    >,
    #[prost(message, optional, tag = "11")]
    pub stripe_charge: ::core::option::Option<
        super::super::super::common::v1::StripeCharge,
    >,
    #[prost(string, optional, tag = "12")]
    pub payment_intent: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompletePaymentResponse {
    #[prost(bool, tag = "1")]
    pub paid: bool,
    #[prost(string, optional, tag = "2")]
    pub failure_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub verification: ::core::option::Option<
        super::super::super::common::v1::StripeVerification,
    >,
    /// True only when collection was handed to an external provider and its final
    /// outcome will arrive asynchronously.
    #[prost(bool, tag = "4")]
    pub submitted: bool,
}
