// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CalculateSpendAllocationBudgetQuotasRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(uint64, tag = "2")]
    pub project_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalculateSpendAllocationBudgetQuotasResponse {
    #[prost(message, repeated, tag = "1")]
    pub quotas: ::prost::alloc::vec::Vec<super::super::super::QuotaConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpendAllocationBudgetContext {
    #[prost(message, repeated, tag = "1")]
    pub usages: ::prost::alloc::vec::Vec<
        super::super::spend_allocation::v1::SpendAllocationUsage,
    >,
    #[prost(message, optional, tag = "2")]
    pub priced_usage: ::core::option::Option<
        super::super::usage_pricer::v1::UsagePricerResponse,
    >,
    #[prost(message, optional, tag = "3")]
    pub package_config: ::core::option::Option<super::super::package::v1::PackageConfig>,
}
