// This file is @generated by prost-build.
/// A Sentry organization account provisioned through a marketplace or channel
/// partner.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartnerAccount {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(enumeration = "PartnerAccountType", tag = "2")]
    pub partner_account_type: i32,
    #[prost(uint64, tag = "3")]
    pub organization_id: u64,
    /// The account identifier assigned by the partner.
    #[prost(string, tag = "4")]
    pub external_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_active: bool,
    /// Unset when the partner does not use token-based API access.
    #[prost(string, optional, tag = "6")]
    pub access_token: ::core::option::Option<::prost::alloc::string::String>,
}
/// The marketplace or channel partner that owns the account relationship.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PartnerAccountType {
    Unspecified = 0,
    Heroku = 1,
    GithubEdu = 2,
    FlyIo = 3,
    Laravel = 4,
    Nintendo = 5,
    Cloudfoundry = 6,
    Github = 7,
    Vercel = 8,
}
impl PartnerAccountType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PARTNER_ACCOUNT_TYPE_UNSPECIFIED",
            Self::Heroku => "PARTNER_ACCOUNT_TYPE_HEROKU",
            Self::GithubEdu => "PARTNER_ACCOUNT_TYPE_GITHUB_EDU",
            Self::FlyIo => "PARTNER_ACCOUNT_TYPE_FLY_IO",
            Self::Laravel => "PARTNER_ACCOUNT_TYPE_LARAVEL",
            Self::Nintendo => "PARTNER_ACCOUNT_TYPE_NINTENDO",
            Self::Cloudfoundry => "PARTNER_ACCOUNT_TYPE_CLOUDFOUNDRY",
            Self::Github => "PARTNER_ACCOUNT_TYPE_GITHUB",
            Self::Vercel => "PARTNER_ACCOUNT_TYPE_VERCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARTNER_ACCOUNT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PARTNER_ACCOUNT_TYPE_HEROKU" => Some(Self::Heroku),
            "PARTNER_ACCOUNT_TYPE_GITHUB_EDU" => Some(Self::GithubEdu),
            "PARTNER_ACCOUNT_TYPE_FLY_IO" => Some(Self::FlyIo),
            "PARTNER_ACCOUNT_TYPE_LARAVEL" => Some(Self::Laravel),
            "PARTNER_ACCOUNT_TYPE_NINTENDO" => Some(Self::Nintendo),
            "PARTNER_ACCOUNT_TYPE_CLOUDFOUNDRY" => Some(Self::Cloudfoundry),
            "PARTNER_ACCOUNT_TYPE_GITHUB" => Some(Self::Github),
            "PARTNER_ACCOUNT_TYPE_VERCEL" => Some(Self::Vercel),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPartnerAccountRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPartnerAccountResponse {
    /// Unset when the organization does not have a partner account.
    #[prost(message, optional, tag = "1")]
    pub partner_account: ::core::option::Option<PartnerAccount>,
}
