// This file is @generated by prost-build.
/// Configuration persisted as JSON by the spend notification data service.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpendNotificationConfig {
    #[prost(string, tag = "1")]
    pub line_item_uid: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub threshold: u32,
    #[prost(message, optional, tag = "3")]
    pub evaluation_expression: ::core::option::Option<SpendNotificationExpression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpendNotificationExpression {
    #[prost(
        oneof = "spend_notification_expression::ExpressionType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8"
    )]
    pub expression_type: ::core::option::Option<
        spend_notification_expression::ExpressionType,
    >,
}
/// Nested message and enum types in `SpendNotificationExpression`.
pub mod spend_notification_expression {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ExpressionType {
        #[prost(message, tag = "1")]
        LineItemUsage(super::LineItemUsageReference),
        #[prost(message, tag = "2")]
        SharedLineItemUsage(super::SharedLineItemUsageReference),
        #[prost(message, tag = "3")]
        UsagePricerResponse(super::UsagePricerResponseReference),
        #[prost(message, tag = "4")]
        RateCardLineItem(super::RateCardLineItemReference),
        #[prost(message, tag = "5")]
        SharedRateCardLineItem(super::SharedRateCardLineItemReference),
        #[prost(message, tag = "6")]
        ContractBudget(super::ContractBudgetReference),
        #[prost(double, tag = "7")]
        Constant(f64),
        #[prost(message, tag = "8")]
        BinaryOp(::prost::alloc::boxed::Box<super::SpendNotificationBinaryOperation>),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LineItemUsageReference {
    #[prost(string, tag = "1")]
    pub line_item_uid: ::prost::alloc::string::String,
    #[prost(enumeration = "LineItemUsageField", tag = "2")]
    pub field: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SharedLineItemUsageReference {
    #[prost(string, tag = "1")]
    pub shared_line_item_uid: ::prost::alloc::string::String,
    #[prost(enumeration = "SharedLineItemUsageField", tag = "2")]
    pub field: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsagePricerResponseReference {
    #[prost(enumeration = "UsagePricerResponseField", tag = "1")]
    pub field: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RateCardLineItemReference {
    #[prost(string, tag = "1")]
    pub line_item_uid: ::prost::alloc::string::String,
    #[prost(enumeration = "RateCardLineItemField", tag = "2")]
    pub field: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SharedRateCardLineItemReference {
    #[prost(string, tag = "1")]
    pub shared_line_item_uid: ::prost::alloc::string::String,
    #[prost(enumeration = "SharedRateCardLineItemField", tag = "2")]
    pub field: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractBudgetReference {
    #[prost(oneof = "contract_budget_reference::Scope", tags = "1, 2")]
    pub scope: ::core::option::Option<contract_budget_reference::Scope>,
}
/// Nested message and enum types in `ContractBudgetReference`.
pub mod contract_budget_reference {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Scope {
        #[prost(string, tag = "1")]
        LineItemUid(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        AllLineItems(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpendNotificationBinaryOperation {
    #[prost(enumeration = "super::super::super::common::v1::Operator", tag = "1")]
    pub operator: i32,
    #[prost(message, optional, boxed, tag = "2")]
    pub left: ::core::option::Option<
        ::prost::alloc::boxed::Box<SpendNotificationExpression>,
    >,
    #[prost(message, optional, boxed, tag = "3")]
    pub right: ::core::option::Option<
        ::prost::alloc::boxed::Box<SpendNotificationExpression>,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LineItemUsageField {
    Unspecified = 0,
    PaygSpendCents = 1,
    PaygQuantity = 2,
    TotalQuantity = 3,
    ReservedSpendCents = 4,
}
impl LineItemUsageField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LINE_ITEM_USAGE_FIELD_UNSPECIFIED",
            Self::PaygSpendCents => "LINE_ITEM_USAGE_FIELD_PAYG_SPEND_CENTS",
            Self::PaygQuantity => "LINE_ITEM_USAGE_FIELD_PAYG_QUANTITY",
            Self::TotalQuantity => "LINE_ITEM_USAGE_FIELD_TOTAL_QUANTITY",
            Self::ReservedSpendCents => "LINE_ITEM_USAGE_FIELD_RESERVED_SPEND_CENTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LINE_ITEM_USAGE_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "LINE_ITEM_USAGE_FIELD_PAYG_SPEND_CENTS" => Some(Self::PaygSpendCents),
            "LINE_ITEM_USAGE_FIELD_PAYG_QUANTITY" => Some(Self::PaygQuantity),
            "LINE_ITEM_USAGE_FIELD_TOTAL_QUANTITY" => Some(Self::TotalQuantity),
            "LINE_ITEM_USAGE_FIELD_RESERVED_SPEND_CENTS" => {
                Some(Self::ReservedSpendCents)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SharedLineItemUsageField {
    Unspecified = 0,
    PaygSpendCents = 1,
    ReservedSpendCents = 2,
}
impl SharedLineItemUsageField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SHARED_LINE_ITEM_USAGE_FIELD_UNSPECIFIED",
            Self::PaygSpendCents => "SHARED_LINE_ITEM_USAGE_FIELD_PAYG_SPEND_CENTS",
            Self::ReservedSpendCents => {
                "SHARED_LINE_ITEM_USAGE_FIELD_RESERVED_SPEND_CENTS"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SHARED_LINE_ITEM_USAGE_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "SHARED_LINE_ITEM_USAGE_FIELD_PAYG_SPEND_CENTS" => Some(Self::PaygSpendCents),
            "SHARED_LINE_ITEM_USAGE_FIELD_RESERVED_SPEND_CENTS" => {
                Some(Self::ReservedSpendCents)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UsagePricerResponseField {
    Unspecified = 0,
    PaygSpendCents = 1,
}
impl UsagePricerResponseField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USAGE_PRICER_RESPONSE_FIELD_UNSPECIFIED",
            Self::PaygSpendCents => "USAGE_PRICER_RESPONSE_FIELD_PAYG_SPEND_CENTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USAGE_PRICER_RESPONSE_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "USAGE_PRICER_RESPONSE_FIELD_PAYG_SPEND_CENTS" => Some(Self::PaygSpendCents),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RateCardLineItemField {
    Unspecified = 0,
    ReservedUnits = 1,
}
impl RateCardLineItemField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RATE_CARD_LINE_ITEM_FIELD_UNSPECIFIED",
            Self::ReservedUnits => "RATE_CARD_LINE_ITEM_FIELD_RESERVED_UNITS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RATE_CARD_LINE_ITEM_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "RATE_CARD_LINE_ITEM_FIELD_RESERVED_UNITS" => Some(Self::ReservedUnits),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SharedRateCardLineItemField {
    Unspecified = 0,
    ReservedCents = 1,
}
impl SharedRateCardLineItemField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SHARED_RATE_CARD_LINE_ITEM_FIELD_UNSPECIFIED",
            Self::ReservedCents => "SHARED_RATE_CARD_LINE_ITEM_FIELD_RESERVED_CENTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SHARED_RATE_CARD_LINE_ITEM_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "SHARED_RATE_CARD_LINE_ITEM_FIELD_RESERVED_CENTS" => {
                Some(Self::ReservedCents)
            }
            _ => None,
        }
    }
}
