// This file is @generated by prost-build.
/// Clears any pending change staged for an organization. No-op if none is
/// staged. Typically used when sales reverses a scheduled downgrade or when a
/// customer's new plan change supersedes the pending one.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearPendingChangeRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearPendingChangeResponse {
    /// True if a pending change existed and was cleared. False if no pending
    /// change was staged at the time of the call.
    #[prost(bool, tag = "1")]
    pub cleared: bool,
}
/// Fetches the active pending change for an organization, if any.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPendingChangeRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPendingChangeResponse {
    /// The active pending change for the org. Unset if no change is currently
    /// staged.
    #[prost(message, optional, tag = "1")]
    pub pending_change: ::core::option::Option<
        super::super::super::common::v1::PendingChange,
    >,
}
