// This file is @generated by prost-build.
/// Configuration for a sponsored contract. The presence of this message on a
/// BillingConfig indicates the contract is sponsored; its absence means it is
/// not.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SponsorshipConfig {
    /// Whether this sponsored Contract is eligible to start trials.
    #[prost(bool, tag = "1")]
    pub can_trial: bool,
    /// Whether this sponsored Contract can checkout.
    #[prost(bool, tag = "2")]
    pub can_checkout: bool,
    #[prost(enumeration = "super::super::super::common::v1::SponsoredType", tag = "3")]
    pub sponsorship_type: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingConfig {
    /// The number-of-months interval the contract was signed under
    /// (1 = monthly, 12 = annual). Frozen for the life of the contract.
    #[prost(uint32, tag = "1")]
    pub month_interval: u32,
    /// Whether the org is allowed to incur pay-as-you-go usage.
    /// Credit-card orgs always support payg; invoiced orgs that should
    /// support it are an explicit override.
    #[prost(bool, tag = "2")]
    pub supports_payg: bool,
    /// Whether this is a managed (sales-assisted) subscription rather than
    /// self-serve.
    #[prost(bool, tag = "3")]
    pub is_managed: bool,
    /// Whether the org has a soft cap: usage past reserved volume is allowed
    /// (and billed) instead of hard-stopping ingestion.
    #[prost(bool, tag = "4")]
    pub has_soft_cap: bool,
    /// Sponsorship configuration. Absent means the contract is not sponsored.
    #[prost(message, optional, tag = "5")]
    pub sponsorship_config: ::core::option::Option<SponsorshipConfig>,
    #[prost(message, optional, tag = "6")]
    pub charge_config: ::core::option::Option<super::v1::ChargeConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractMetadata {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    /// The set of BillingRules that the BillingRulesEngine has to execute for this contract.
    #[prost(string, tag = "3")]
    pub ruleset_version: ::prost::alloc::string::String,
    /// Catch-all for overrides and information not covered above.
    #[prost(message, optional, tag = "4")]
    pub custom_options: ::core::option::Option<super::v1::MetadataOptions>,
    #[prost(string, tag = "5")]
    pub package_uid: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "6")]
    pub previous_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PricingConfig {
    /// Determines when to reset quotas and charge the subscription price.
    #[prost(message, optional, tag = "1")]
    pub billing_period_start_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "2")]
    pub billing_period_end_date: ::core::option::Option<super::v1::Date>,
    /// Determines when the on demand period for invoicing the organization starts and ends, even for annual plans we bill ondemand monthly
    #[prost(message, optional, tag = "3")]
    pub ondemand_period_start_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "4")]
    pub ondemand_period_end_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "5")]
    pub usage_watermark_ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "6")]
    pub user_config: ::prost::alloc::vec::Vec<super::v1::UserConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<ContractMetadata>,
    #[prost(message, optional, tag = "2")]
    pub billing_config: ::core::option::Option<BillingConfig>,
    #[prost(message, optional, tag = "3")]
    pub pricing_config: ::core::option::Option<PricingConfig>,
    #[prost(message, optional, tag = "4")]
    pub retention_config: ::core::option::Option<super::v1::RetentionConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContractRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(string, tag = "2")]
    pub package_uid: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub user_configs: ::prost::alloc::vec::Vec<super::v1::UserConfig>,
    #[prost(message, repeated, tag = "4")]
    pub line_items: ::prost::alloc::vec::Vec<super::v1::InvoiceLineItem>,
    #[prost(message, optional, tag = "5")]
    pub address: ::core::option::Option<super::super::super::common::v1::Address>,
    /// The customer's chosen cadence. Must be one of the package's
    /// supported_month_intervals. If unset, defaults to the package's first
    /// supported interval.
    #[prost(uint32, tag = "6")]
    pub month_interval: u32,
    /// How the contract is billed. If unset (BILLING_TYPE_UNSPECIFIED), the
    /// contract defaults to credit-card.
    #[prost(enumeration = "super::v1::BillingType", tag = "7")]
    pub billing_type: i32,
    /// Whether usage past reserved volume is allowed (and billed) instead of
    /// hard-stopping ingestion.
    #[prost(bool, tag = "8")]
    pub has_soft_cap: bool,
    /// The tax provider's reference for the tax document opened for this invoice.
    /// When set, the contract service records it on the created invoice as a
    /// pending tax transaction atomically with invoice creation. Unset means no
    /// tax document was opened.
    #[prost(string, optional, tag = "9")]
    pub tax_transaction_code: ::core::option::Option<::prost::alloc::string::String>,
    /// The sponsored type of the contract. If unset, then this is a non-sponsored
    /// contract.
    #[prost(
        enumeration = "super::super::super::common::v1::SponsoredType",
        optional,
        tag = "10"
    )]
    pub sponsorship_type: ::core::option::Option<i32>,
    /// The customer's tax registration number (e.g. VAT ID) on file.
    #[prost(string, optional, tag = "11")]
    pub tax_number: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether the tax provider placed this invoice under reverse charge.
    #[prost(bool, tag = "12")]
    pub is_reverse_charge: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateContractResponse {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub invoice_id: u64,
    #[prost(string, tag = "3")]
    pub invoice_guid: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub needs_charge: bool,
    #[prost(uint64, tag = "5")]
    pub amount_billed: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAllContractsForOrganizationRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllContractsForOrganizationResponse {
    #[prost(message, repeated, tag = "1")]
    pub contracts: ::prost::alloc::vec::Vec<Contract>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetContractRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    /// If provided, returns the Contract active on this date. Otherwise, returns the current Contract.
    #[prost(message, optional, tag = "2")]
    pub date: ::core::option::Option<super::super::super::Date>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSpecificContractRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetContractResponse {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Contract>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUninvoicedContractsRequest {
    /// Returns Contracts whose current billing period ends before this time and
    /// have not yet been invoiced for the current period.
    #[prost(message, optional, tag = "1")]
    pub current_ts: ::core::option::Option<::prost_types::Timestamp>,
    /// Maximum number of contracts to return in the response. If more contracts
    /// match the request than this limit, the response will have truncated set
    /// to true.
    #[prost(uint32, tag = "2")]
    pub max_items: u32,
    #[prost(uint32, optional, tag = "3")]
    pub offset: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUninvoicedContractsResponse {
    /// True if additional matching contracts existed beyond max_items and were
    /// not included in this response.
    #[prost(bool, tag = "1")]
    pub truncated: bool,
    #[prost(uint64, repeated, tag = "2")]
    pub contract_ids: ::prost::alloc::vec::Vec<u64>,
}
