// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddPricedUsageToSnapshotRequest {
    #[prost(uint64, tag = "1")]
    pub snapshot_id: u64,
    #[prost(message, optional, tag = "2")]
    pub usage_pricer_response: ::core::option::Option<
        super::super::usage_pricer::v1::UsagePricerResponse,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddPricedUsageToSnapshotResponse {
    #[prost(bool, tag = "1")]
    pub updated: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsageSnapshot {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    #[prost(uint64, tag = "3")]
    pub contract_id: u64,
    #[prost(message, optional, tag = "4")]
    pub billing_usage_response: ::core::option::Option<
        super::super::usage::v1::GetUsageResponse,
    >,
    #[prost(message, optional, tag = "5")]
    pub billing_usage_by_project_response: ::core::option::Option<
        super::super::usage::v1::GetUsageByProjectResponse,
    >,
    #[prost(message, optional, tag = "6")]
    pub usage_pricer_response: ::core::option::Option<
        super::super::usage_pricer::v1::UsagePricerResponse,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateUsageSnapshotRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(uint64, tag = "2")]
    pub contract_id: u64,
    #[prost(message, optional, tag = "3")]
    pub billing_usage_response: ::core::option::Option<
        super::super::usage::v1::GetUsageResponse,
    >,
    #[prost(message, optional, tag = "4")]
    pub billing_usage_by_project_response: ::core::option::Option<
        super::super::usage::v1::GetUsageByProjectResponse,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateUsageSnapshotResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<UsageSnapshot>,
    #[prost(bool, tag = "2")]
    pub created: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageSnapshotRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageSnapshotByIdRequest {
    #[prost(uint64, tag = "1")]
    pub snapshot_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageSnapshotResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<UsageSnapshot>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageSnapshotsRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageSnapshotsResponse {
    #[prost(message, repeated, tag = "1")]
    pub snapshots: ::prost::alloc::vec::Vec<UsageSnapshot>,
}
