// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureChargeRequest {
    #[prost(bool, tag = "1")]
    pub perform: bool,
    #[prost(int64, tag = "2")]
    pub amount: i64,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub payment_intent: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub current_ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, optional, tag = "7")]
    pub invoice_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureChargeResponse {
    #[prost(bool, tag = "1")]
    pub paid: bool,
    #[prost(string, optional, tag = "2")]
    pub failure_code: ::core::option::Option<::prost::alloc::string::String>,
}
