// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrgsWithUsageRequest {
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional filter for specific data categories.
    /// When empty, usage for all categories is queried.
    #[prost(enumeration = "super::super::super::DataCategory", repeated, tag = "4")]
    pub categories: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrgsWithUsageResponse {
    #[prost(uint64, repeated, tag = "1")]
    pub organization_ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CategoryUsage {
    #[prost(enumeration = "super::super::super::DataCategory", tag = "1")]
    pub category: i32,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<super::super::super::UsageData>,
}
/// Usage data for a single day.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DailyUsage {
    #[prost(message, optional, tag = "1")]
    pub date: ::core::option::Option<super::super::super::Date>,
    #[prost(message, repeated, tag = "2")]
    pub usage: ::prost::alloc::vec::Vec<CategoryUsage>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CategorySeatUsage {
    #[prost(enumeration = "super::super::super::SeatCategory", tag = "1")]
    pub category: i32,
    #[prost(uint64, tag = "2")]
    pub count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageResponse {
    /// Usage broken down by day, each containing per-category usage.
    #[prost(message, repeated, tag = "1")]
    pub days: ::prost::alloc::vec::Vec<DailyUsage>,
    #[prost(message, repeated, tag = "2")]
    pub seats: ::prost::alloc::vec::Vec<CategorySeatUsage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional filter for specific data categories.
    /// When empty, usage for all categories is returned.
    #[prost(enumeration = "super::super::super::DataCategory", repeated, tag = "4")]
    pub categories: ::prost::alloc::vec::Vec<i32>,
}
