// This file is @generated by prost-build.
/// Marks a contract's seat tracker as CLOSED, preventing further seat actions.
/// Called during rollover before writing seats to the new contract.
/// Silently succeeds if no tracker exists for the contract.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseContractRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseContractResponse {}
/// Identifies a billable seat (e.g. a monitor, uptime detector, or seer
/// contributor) within an organization and project.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeatObject {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(uint64, tag = "2")]
    pub project_id: u64,
    #[prost(enumeration = "super::super::super::SeatCategory", tag = "3")]
    pub seat_category: i32,
    /// Human-readable label for the seat (e.g. monitor name).
    #[prost(string, tag = "4")]
    pub external_product_display_name: ::prost::alloc::string::String,
    /// Unique identifier for the seat within its category and project
    /// (e.g. monitor slug). Used as the key for all state lookups.
    #[prost(string, tag = "5")]
    pub external_product_identifier: ::prost::alloc::string::String,
}
/// Reconstructed point-in-time state for a single seat, derived by replaying
/// its action history (last action wins).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeatState {
    #[prost(string, tag = "1")]
    pub external_product_identifier: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::super::common::v1::SeatStatus", tag = "2")]
    pub current_status: i32,
    /// Timestamp of the first-ever action for this seat on the contract.
    #[prost(message, optional, tag = "3")]
    pub created_ts: ::core::option::Option<::prost_types::Timestamp>,
    /// Timestamp of the most recent action for this seat on the contract.
    #[prost(message, optional, tag = "4")]
    pub last_action_ts: ::core::option::Option<::prost_types::Timestamp>,
    /// When the state was read (server clock). Useful for cache staleness checks.
    #[prost(message, optional, tag = "5")]
    pub read_ts: ::core::option::Option<::prost_types::Timestamp>,
}
/// A single immutable record of a seat state transition, stored as an
/// append-only audit log.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeatActionRecord {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    #[prost(uint64, tag = "3")]
    pub project_id: u64,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "super::super::super::common::v1::SeatStatus", tag = "5")]
    pub status: i32,
    #[prost(uint32, tag = "6")]
    pub seat_category: u32,
    #[prost(string, tag = "7")]
    pub external_product_identifier: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub external_product_display_name: ::prost::alloc::string::String,
}
/// All action records for a single external product identifier on a contract,
/// ordered chronologically.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalProductSeatActivity {
    #[prost(string, tag = "1")]
    pub external_product_identifier: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub seat_actions: ::prost::alloc::vec::Vec<SeatActionRecord>,
}
/// Input item for PerformSeatActions: pairs a seat with its desired new state.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeatActionItem {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<SeatObject>,
    #[prost(message, optional, tag = "2")]
    pub seat_state: ::core::option::Option<SeatState>,
}
/// The earliest-ever recorded action timestamp for a seat across all contracts
/// in an organization. Used to sort seats by seniority during rollover.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OriginalSeatDate {
    #[prost(string, tag = "1")]
    pub external_product_identifier: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub created_ts: ::core::option::Option<::prost_types::Timestamp>,
}
/// Returns each seat's earliest-ever recorded action timestamp across the
/// entire organization (not scoped to a single contract). Used during contract
/// rollover to sort seats by seniority when capacity is tight.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOriginalSeatDatesRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(enumeration = "super::super::super::SeatCategory", tag = "2")]
    pub seat_category: i32,
    #[prost(string, repeated, tag = "3")]
    pub external_product_identifiers: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOriginalSeatDatesResponse {
    #[prost(message, repeated, tag = "1")]
    pub original_seat_dates: ::prost::alloc::vec::Vec<OriginalSeatDate>,
}
/// Returns every seat action recorded for a contract, grouped by product
/// identifier and ordered chronologically. This is the raw audit log of all
/// state transitions during a billing period.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatActivityHistoryRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSeatActivityHistoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub seat_activities: ::prost::alloc::vec::Vec<ExternalProductSeatActivity>,
    #[prost(message, optional, tag = "2")]
    pub read_ts: ::core::option::Option<::prost_types::Timestamp>,
}
/// Checks whether a contract has a seat tracking record and whether it is
/// ACTIVE. Used by the seats service to decide whether to bootstrap a new
/// tracker or trigger a rollover from a previous contract.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatContractStateRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatContractStateResponse {
    #[prost(bool, tag = "1")]
    pub exists: bool,
    #[prost(bool, tag = "2")]
    pub is_active: bool,
}
/// Returns the current status of a single seat by replaying its action history
/// on the given contract (last action wins). Returns DNE if no actions exist.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStateRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(message, optional, tag = "2")]
    pub seat_object: ::core::option::Option<SeatObject>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStateResponse {
    #[prost(message, optional, tag = "1")]
    pub seat_state: ::core::option::Option<SeatState>,
}
/// The single write path for all seat mutations. Appends action records in bulk
/// under a transaction. Does NOT check budgets or eligibility — that is the
/// caller's responsibility.
///
/// Rejects duplicate identifiers within a single request. Requires an ACTIVE
/// contract tracker unless create_new_contract_state is set.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PerformSeatActionsRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub seat_actions: ::prost::alloc::vec::Vec<SeatActionItem>,
    /// When true, creates a new ACTIVE contract tracker for this contract.
    /// Fails if one already exists (used for first-time setup and rollover).
    #[prost(bool, tag = "3")]
    pub create_new_contract_state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PerformSeatActionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub current_seat_states: ::prost::alloc::vec::Vec<SeatState>,
}
