// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsagePricerRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPriceForContractRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(message, optional, tag = "2")]
    pub usage_start_watermark_ts: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LineItemUsageSummary {
    /// Refers to uid in sentry_protos.billing.v1.common.v1.LineItemDetails
    #[prost(string, tag = "1")]
    pub line_item_uid: ::prost::alloc::string::String,
    /// Net cents consumed by this line item in the billing period (after credits/trials applied).
    #[prost(uint64, tag = "2")]
    pub payg_spend_cents: u64,
    /// How much of the line item was consumed (in the line item's units)
    #[prost(uint64, tag = "3")]
    pub quantity: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharedLineItemUsageSummary {
    /// Net cents consumed across all SKUs in this shared budget (after credits/trials applied).
    #[prost(uint64, tag = "1")]
    pub payg_spend_cents: u64,
    /// Line item breakdown within shared budget
    #[prost(message, repeated, tag = "2")]
    pub line_item_summaries: ::prost::alloc::vec::Vec<LineItemUsageSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsagePricerResponse {
    #[prost(message, repeated, tag = "3")]
    pub line_item_summaries: ::prost::alloc::vec::Vec<LineItemUsageSummary>,
    #[prost(message, repeated, tag = "4")]
    pub shared_line_item_summaries: ::prost::alloc::vec::Vec<SharedLineItemUsageSummary>,
    #[prost(message, optional, tag = "5")]
    pub last_usage_ts: ::core::option::Option<::prost_types::Timestamp>,
}
