// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSandboxRequest {
    /// SandboxTemplate to instantiate. The router's default is used when unset.
    #[prost(string, optional, tag = "1")]
    pub template_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Namespace to create the sandbox in. The router's default is used when unset.
    #[prost(string, optional, tag = "2")]
    pub namespace: ::core::option::Option<::prost::alloc::string::String>,
    /// Time-to-live in seconds before the sandbox is automatically deleted. The
    /// router's default is used when unset.
    #[prost(int32, optional, tag = "3")]
    pub ttl_seconds: ::core::option::Option<i32>,
    /// GitHub access token to make available inside the sandbox for cloning and
    /// interacting with repositories. When unset, no token is provisioned.
    #[prost(string, optional, tag = "4")]
    pub github_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSandboxResponse {
    /// Identifier for the sandbox, used to route subsequent requests to it.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// Namespace the sandbox was created in.
    #[prost(string, tag = "2")]
    pub namespace: ::prost::alloc::string::String,
    /// SandboxTemplate the sandbox was instantiated from.
    #[prost(string, tag = "3")]
    pub template_name: ::prost::alloc::string::String,
    /// When the sandbox will be automatically deleted.
    #[prost(message, optional, tag = "4")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSandboxRequest {
    /// Identifier of the sandbox to delete.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// Namespace the sandbox lives in. The router's default is used when unset.
    #[prost(string, optional, tag = "2")]
    pub namespace: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSandboxResponse {}
/// A shell command executed inside a sandbox, together with its result.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShellCommand {
    /// Identifier for this command, assigned on creation and used to refer to it
    /// in subsequent requests.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Name of the sandbox to run the command in.
    #[prost(string, tag = "2")]
    pub sandbox_name: ::prost::alloc::string::String,
    /// The command to execute, as an argv list. Executed directly rather than
    /// through a shell, so no quoting or expansion is applied.
    #[prost(string, repeated, tag = "3")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Exit code returned by the command. Set once the command has completed.
    #[prost(int32, tag = "4")]
    pub exit_code: i32,
    /// Handle to the command's standard input, for writing.
    #[prost(message, optional, tag = "5")]
    pub stdin: ::core::option::Option<File>,
    /// Handle to the command's standard output, for reading.
    #[prost(message, optional, tag = "6")]
    pub stdout: ::core::option::Option<File>,
    /// Handle to the command's standard error, for reading.
    #[prost(message, optional, tag = "7")]
    pub stderr: ::core::option::Option<File>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartRequest {
    /// Name of the sandbox to run the command in.
    #[prost(string, tag = "1")]
    pub sandbox_name: ::prost::alloc::string::String,
    /// The command to execute, as an argv list.
    #[prost(string, repeated, tag = "2")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartResponse {
    /// The started command.
    #[prost(message, optional, tag = "1")]
    pub shell_command: ::core::option::Option<ShellCommand>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PollRequest {
    /// Identifier of the command to fetch the current state of.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PollResponse {
    /// The command with its current state.
    #[prost(message, optional, tag = "1")]
    pub shell_command: ::core::option::Option<ShellCommand>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignalRequest {
    /// Identifier of the command to signal.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The signal to send to the running command (e.g. SIGTERM=15, SIGKILL=9).
    #[prost(int32, tag = "2")]
    pub signal: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignalResponse {}
/// A file opened inside a sandbox, modeled on Go's os.File. Open returns a
/// handle that the caller reads from, writes to, and finally closes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct File {
    /// Identifier for the open file, assigned on open and used to refer to it in
    /// subsequent reads, writes, and the close.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Name of the sandbox the file lives in.
    #[prost(string, tag = "2")]
    pub sandbox_name: ::prost::alloc::string::String,
    /// Path of the file within the sandbox.
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenRequest {
    /// Name of the sandbox the file lives in.
    #[prost(string, tag = "1")]
    pub sandbox_name: ::prost::alloc::string::String,
    /// Path of the file within the sandbox.
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// Flags controlling how the file is opened, mirroring the flag argument to
    /// Go's os.OpenFile (e.g. read-only, write-only, create, append, truncate).
    #[prost(int32, tag = "3")]
    pub flags: i32,
    /// Permission bits to apply when the file is created, mirroring the perm
    /// argument to Go's os.OpenFile.
    #[prost(uint32, tag = "4")]
    pub perm: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenResponse {
    /// The opened file handle.
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<File>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadRequest {
    /// Identifier of the open file to read from.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Maximum number of bytes to read. A response shorter than this indicates
    /// end of file.
    #[prost(int64, tag = "2")]
    pub size: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadResponse {
    /// Bytes read from the file. Empty at end of file.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteRequest {
    /// Identifier of the open file to write to.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Bytes to write to the file.
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteResponse {
    /// Number of bytes written.
    #[prost(int64, tag = "1")]
    pub written: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseRequest {
    /// Identifier of the open file to close.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseResponse {}
/// Generated client implementations.
pub mod sandbox_router_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SandboxRouterService orchestrates ephemeral sandbox pods that run AI coding
    /// agents on customer repositories.
    #[derive(Debug, Clone)]
    pub struct SandboxRouterServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SandboxRouterServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SandboxRouterServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SandboxRouterServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SandboxRouterServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// CreateSandbox provisions a sandbox and waits for it to become ready.
        pub async fn create_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CreateSandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "CreateSandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DeleteSandbox tears down a sandbox and its resources.
        pub async fn delete_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/DeleteSandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "DeleteSandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Start runs a shell command inside a sandbox.
        pub async fn start(
            &mut self,
            request: impl tonic::IntoRequest<super::StartRequest>,
        ) -> std::result::Result<tonic::Response<super::StartResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Start",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Start",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Poll fetches the current state of a running command.
        pub async fn poll(
            &mut self,
            request: impl tonic::IntoRequest<super::PollRequest>,
        ) -> std::result::Result<tonic::Response<super::PollResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Poll",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Poll",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Signal sends a signal to a running command.
        pub async fn signal(
            &mut self,
            request: impl tonic::IntoRequest<super::SignalRequest>,
        ) -> std::result::Result<tonic::Response<super::SignalResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Signal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Signal",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Open opens a file inside a sandbox and returns a handle to it.
        pub async fn open(
            &mut self,
            request: impl tonic::IntoRequest<super::OpenRequest>,
        ) -> std::result::Result<tonic::Response<super::OpenResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Open",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Open",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Read reads bytes from an open file.
        pub async fn read(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadRequest>,
        ) -> std::result::Result<tonic::Response<super::ReadResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Read",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Read",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Write writes bytes to an open file.
        pub async fn write(
            &mut self,
            request: impl tonic::IntoRequest<super::WriteRequest>,
        ) -> std::result::Result<tonic::Response<super::WriteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Write",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Write",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Close closes an open file.
        pub async fn close(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseRequest>,
        ) -> std::result::Result<tonic::Response<super::CloseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Close",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "Close",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod sandbox_router_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SandboxRouterServiceServer.
    #[async_trait]
    pub trait SandboxRouterService: std::marker::Send + std::marker::Sync + 'static {
        /// CreateSandbox provisions a sandbox and waits for it to become ready.
        async fn create_sandbox(
            &self,
            request: tonic::Request<super::CreateSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSandboxResponse>,
            tonic::Status,
        >;
        /// DeleteSandbox tears down a sandbox and its resources.
        async fn delete_sandbox(
            &self,
            request: tonic::Request<super::DeleteSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSandboxResponse>,
            tonic::Status,
        >;
        /// Start runs a shell command inside a sandbox.
        async fn start(
            &self,
            request: tonic::Request<super::StartRequest>,
        ) -> std::result::Result<tonic::Response<super::StartResponse>, tonic::Status>;
        /// Poll fetches the current state of a running command.
        async fn poll(
            &self,
            request: tonic::Request<super::PollRequest>,
        ) -> std::result::Result<tonic::Response<super::PollResponse>, tonic::Status>;
        /// Signal sends a signal to a running command.
        async fn signal(
            &self,
            request: tonic::Request<super::SignalRequest>,
        ) -> std::result::Result<tonic::Response<super::SignalResponse>, tonic::Status>;
        /// Open opens a file inside a sandbox and returns a handle to it.
        async fn open(
            &self,
            request: tonic::Request<super::OpenRequest>,
        ) -> std::result::Result<tonic::Response<super::OpenResponse>, tonic::Status>;
        /// Read reads bytes from an open file.
        async fn read(
            &self,
            request: tonic::Request<super::ReadRequest>,
        ) -> std::result::Result<tonic::Response<super::ReadResponse>, tonic::Status>;
        /// Write writes bytes to an open file.
        async fn write(
            &self,
            request: tonic::Request<super::WriteRequest>,
        ) -> std::result::Result<tonic::Response<super::WriteResponse>, tonic::Status>;
        /// Close closes an open file.
        async fn close(
            &self,
            request: tonic::Request<super::CloseRequest>,
        ) -> std::result::Result<tonic::Response<super::CloseResponse>, tonic::Status>;
    }
    /// SandboxRouterService orchestrates ephemeral sandbox pods that run AI coding
    /// agents on customer repositories.
    #[derive(Debug)]
    pub struct SandboxRouterServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SandboxRouterServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for SandboxRouterServiceServer<T>
    where
        T: SandboxRouterService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CreateSandbox" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSandboxSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::CreateSandboxRequest>
                    for CreateSandboxSvc<T> {
                        type Response = super::CreateSandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateSandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::create_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/DeleteSandbox" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSandboxSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::DeleteSandboxRequest>
                    for DeleteSandboxSvc<T> {
                        type Response = super::DeleteSandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteSandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::delete_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Start" => {
                    #[allow(non_camel_case_types)]
                    struct StartSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::StartRequest> for StartSvc<T> {
                        type Response = super::StartResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::start(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Poll" => {
                    #[allow(non_camel_case_types)]
                    struct PollSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::PollRequest> for PollSvc<T> {
                        type Response = super::PollResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PollRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::poll(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PollSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Signal" => {
                    #[allow(non_camel_case_types)]
                    struct SignalSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::SignalRequest>
                    for SignalSvc<T> {
                        type Response = super::SignalResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SignalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::signal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SignalSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Open" => {
                    #[allow(non_camel_case_types)]
                    struct OpenSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::OpenRequest> for OpenSvc<T> {
                        type Response = super::OpenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OpenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::open(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = OpenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Read" => {
                    #[allow(non_camel_case_types)]
                    struct ReadSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::ReadRequest> for ReadSvc<T> {
                        type Response = super::ReadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Write" => {
                    #[allow(non_camel_case_types)]
                    struct WriteSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::WriteRequest> for WriteSvc<T> {
                        type Response = super::WriteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WriteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::write(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WriteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/Close" => {
                    #[allow(non_camel_case_types)]
                    struct CloseSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::CloseRequest> for CloseSvc<T> {
                        type Response = super::CloseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CloseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::close(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CloseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SandboxRouterServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.seer.v2alpha.SandboxRouterService";
    impl<T> tonic::server::NamedService for SandboxRouterServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// A model that Seer can use to serve requests.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Model {
    /// The provider-facing model name. This is the identifier used to request
    /// the model, e.g. "claude-opus-4-8@default" or "gemini-2.5-pro".
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The provider that serves the model.
    #[prost(enumeration = "Provider", tag = "2")]
    pub provider: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModelsResponse {
    /// The models currently available to Seer.
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<Model>,
}
/// The provider that serves a model. Mirrors Seer's LlmProviderType.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Provider {
    Unspecified = 0,
    Openai = 1,
    Anthropic = 2,
    Gemini = 3,
}
impl Provider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROVIDER_UNSPECIFIED",
            Self::Openai => "PROVIDER_OPENAI",
            Self::Anthropic => "PROVIDER_ANTHROPIC",
            Self::Gemini => "PROVIDER_GEMINI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "PROVIDER_OPENAI" => Some(Self::Openai),
            "PROVIDER_ANTHROPIC" => Some(Self::Anthropic),
            "PROVIDER_GEMINI" => Some(Self::Gemini),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod seer_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SeerService exposes Seer's capabilities over RPC.
    #[derive(Debug, Clone)]
    pub struct SeerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SeerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SeerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SeerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SeerServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetModels returns the models currently available to Seer.
        pub async fn get_models(
            &mut self,
            request: impl tonic::IntoRequest<super::GetModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SeerService/GetModels",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SeerService",
                        "GetModels",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod seer_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SeerServiceServer.
    #[async_trait]
    pub trait SeerService: std::marker::Send + std::marker::Sync + 'static {
        /// GetModels returns the models currently available to Seer.
        async fn get_models(
            &self,
            request: tonic::Request<super::GetModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelsResponse>,
            tonic::Status,
        >;
    }
    /// SeerService exposes Seer's capabilities over RPC.
    #[derive(Debug)]
    pub struct SeerServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SeerServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SeerServiceServer<T>
    where
        T: SeerService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.seer.v2alpha.SeerService/GetModels" => {
                    #[allow(non_camel_case_types)]
                    struct GetModelsSvc<T: SeerService>(pub Arc<T>);
                    impl<
                        T: SeerService,
                    > tonic::server::UnaryService<super::GetModelsRequest>
                    for GetModelsSvc<T> {
                        type Response = super::GetModelsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetModelsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SeerService>::get_models(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetModelsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SeerServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.seer.v2alpha.SeerService";
    impl<T> tonic::server::NamedService for SeerServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
