// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClaimSpendNotificationRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(uint64, tag = "2")]
    pub contract_id: u64,
    #[prost(uint64, tag = "3")]
    pub notification_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClaimSpendNotificationResponse {
    #[prost(bool, tag = "1")]
    pub claimed: bool,
}
/// Configuration persisted as JSON by the spend notification data service.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpendNotificationConfig {
    #[prost(uint32, tag = "1")]
    pub threshold: u32,
    #[prost(enumeration = "SpendNotificationBudgetType", tag = "2")]
    pub budget_type: i32,
    #[prost(oneof = "spend_notification_config::LineItems", tags = "3, 4")]
    pub line_items: ::core::option::Option<spend_notification_config::LineItems>,
}
/// Nested message and enum types in `SpendNotificationConfig`.
pub mod spend_notification_config {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum LineItems {
        #[prost(message, tag = "3")]
        SpecificItems(super::LineItemUids),
        #[prost(message, tag = "4")]
        AllItems(()),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpendNotification {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<SpendNotificationConfig>,
    #[prost(bool, tag = "4")]
    pub is_enabled: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LineItemUids {
    #[prost(string, repeated, tag = "1")]
    pub uids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpendNotificationBudgetType {
    Unspecified = 0,
    Reserved = 1,
    Payg = 2,
}
impl SpendNotificationBudgetType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SPEND_NOTIFICATION_BUDGET_TYPE_UNSPECIFIED",
            Self::Reserved => "SPEND_NOTIFICATION_BUDGET_TYPE_RESERVED",
            Self::Payg => "SPEND_NOTIFICATION_BUDGET_TYPE_PAYG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SPEND_NOTIFICATION_BUDGET_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SPEND_NOTIFICATION_BUDGET_TYPE_RESERVED" => Some(Self::Reserved),
            "SPEND_NOTIFICATION_BUDGET_TYPE_PAYG" => Some(Self::Payg),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSpendNotificationsRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "3")]
    pub is_enabled: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpendNotificationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub notifications: ::prost::alloc::vec::Vec<SpendNotification>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertSpendNotificationRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<SpendNotificationConfig>,
    #[prost(bool, optional, tag = "3")]
    pub is_enabled: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertSpendNotificationResponse {
    #[prost(message, optional, tag = "1")]
    pub notification: ::core::option::Option<SpendNotification>,
}
