// This file is @generated by prost-build.
/// Blended keep-rate for an organization. Derived from the current contract's
/// dynamically sampled line item: max(reserved volume, current-period usage)
/// mapped onto the sampling table. Unlimited reserved collapses to usage.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBlendedSampleRateRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetBlendedSampleRateResponse {
    /// Unset when there is no current contract, or the package has no
    /// LINE_ITEM_TAG_IS_DYNAMICALLY_SAMPLED line item. Keep-rates are always
    /// greater than zero; 0.0 is not a sentinel.
    #[prost(double, optional, tag = "1")]
    pub sample_rate: ::core::option::Option<f64>,
}
