// This file is @generated by prost-build.
/// Configuration for a sponsored contract. The presence of this message on a
/// BillingConfig indicates the contract is sponsored; its absence means it is
/// not.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SponsorshipConfig {
    /// Whether this sponsored Contract is eligible to start trials.
    #[prost(bool, tag = "1")]
    pub can_trial: bool,
    /// Whether this sponsored Contract can checkout.
    #[prost(bool, tag = "2")]
    pub can_checkout: bool,
    #[prost(enumeration = "super::super::super::common::v1::SponsoredType", tag = "3")]
    pub sponsorship_type: i32,
}
/// Pay-as-you-go configuration. The presence of this message means the org may
/// incur payg usage; its absence means it may not.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaygConfig {
    /// Whether we charge payg spend ourselves, against a card on file. When
    /// false, payg is still incurred but billed outside the platform.
    #[prost(bool, tag = "1")]
    pub charged: bool,
}
/// Billed directly by us, on a card the customer manages. Payg is always both
/// permitted and charged, so there is nothing further to configure.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreditCardConfig {}
/// Invoiced by us, under a sales-negotiated agreement.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvoicedConfig {
    /// Absent means the org may not incur payg at all.
    #[prost(message, optional, tag = "1")]
    pub payg: ::core::option::Option<PaygConfig>,
}
/// Billed by a third-party marketplace.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartnerConfig {
    /// Whether the marketplace provisions through the channel flow, which leaves
    /// the customer able to change their own plan.
    #[prost(bool, tag = "1")]
    pub self_serve: bool,
    /// How is the partner is invoiced?
    #[prost(enumeration = "PartnerBillingStrategy", tag = "2")]
    pub billing_strategy: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingConfig {
    /// The number-of-months interval the contract was signed under
    /// (1 = monthly, 12 = annual). Frozen for the life of the contract.
    #[prost(uint32, tag = "1")]
    pub month_interval: u32,
    /// Sponsorship configuration. Absent means the contract is not sponsored.
    /// Orthogonal to `billing`: a sponsored contract is still billed through one
    /// of the arrangements below, and some are sponsored by the same marketplace
    /// that bills them.
    #[prost(message, optional, tag = "5")]
    pub sponsorship_config: ::core::option::Option<SponsorshipConfig>,
    /// Which arrangement bills the contract. Each arrangement carries only the
    /// configuration that applies to it. Unset means none is recorded.
    #[prost(oneof = "billing_config::Billing", tags = "2, 3, 4")]
    pub billing: ::core::option::Option<billing_config::Billing>,
}
/// Nested message and enum types in `BillingConfig`.
pub mod billing_config {
    /// Which arrangement bills the contract. Each arrangement carries only the
    /// configuration that applies to it. Unset means none is recorded.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Billing {
        #[prost(message, tag = "2")]
        CreditCard(super::CreditCardConfig),
        #[prost(message, tag = "3")]
        Invoiced(super::InvoicedConfig),
        #[prost(message, tag = "4")]
        Partner(super::PartnerConfig),
    }
}
/// The invoicing and collection behavior for a partner-billed contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PartnerBillingStrategy {
    Unspecified = 0,
    /// The partner bills the customer independently. The platform records a $0
    /// invoice.
    Invoiced = 1,
    /// The platform calculates the invoice and submits it to Vercel.
    Vercel = 2,
}
impl PartnerBillingStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PARTNER_BILLING_STRATEGY_UNSPECIFIED",
            Self::Invoiced => "PARTNER_BILLING_STRATEGY_INVOICED",
            Self::Vercel => "PARTNER_BILLING_STRATEGY_VERCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARTNER_BILLING_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
            "PARTNER_BILLING_STRATEGY_INVOICED" => Some(Self::Invoiced),
            "PARTNER_BILLING_STRATEGY_VERCEL" => Some(Self::Vercel),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractMetadata {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    /// Catch-all for overrides and information not covered above.
    #[prost(message, optional, tag = "4")]
    pub custom_options: ::core::option::Option<super::v1::MetadataOptions>,
    #[prost(string, tag = "5")]
    pub package_uid: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "6")]
    pub previous_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PricingConfig {
    /// Determines when to reset quotas and charge the subscription price.
    #[prost(message, optional, tag = "1")]
    pub billing_period_start_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "2")]
    pub billing_period_end_date: ::core::option::Option<super::v1::Date>,
    /// Determines when the on demand period for invoicing the organization starts and ends, even for annual plans we bill ondemand monthly
    #[prost(message, optional, tag = "3")]
    pub ondemand_period_start_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "4")]
    pub ondemand_period_end_date: ::core::option::Option<super::v1::Date>,
    #[prost(message, optional, tag = "5")]
    pub usage_watermark_ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "6")]
    pub user_config: ::prost::alloc::vec::Vec<super::v1::UserConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<ContractMetadata>,
    #[prost(message, optional, tag = "2")]
    pub billing_config: ::core::option::Option<BillingConfig>,
    #[prost(message, optional, tag = "3")]
    pub pricing_config: ::core::option::Option<PricingConfig>,
    #[prost(message, optional, tag = "4")]
    pub retention_config: ::core::option::Option<super::v1::RetentionConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContractRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(string, tag = "2")]
    pub package_uid: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub user_configs: ::prost::alloc::vec::Vec<super::v1::UserConfig>,
    #[prost(message, repeated, tag = "4")]
    pub line_items: ::prost::alloc::vec::Vec<super::v1::InvoiceLineItem>,
    #[prost(message, optional, tag = "5")]
    pub address: ::core::option::Option<super::super::super::common::v1::Address>,
    /// The customer's chosen cadence. Must be one of the package's
    /// supported_month_intervals. If unset, defaults to the package's first
    /// supported interval.
    #[prost(uint32, tag = "6")]
    pub month_interval: u32,
    /// The tax provider's reference for the tax document opened for this invoice.
    /// When set, the contract service records it on the created invoice as a
    /// pending tax transaction atomically with invoice creation. Unset means no
    /// tax document was opened.
    #[prost(string, optional, tag = "9")]
    pub tax_transaction_code: ::core::option::Option<::prost::alloc::string::String>,
    /// The sponsored type of the contract. If unset, then this is a non-sponsored
    /// contract.
    #[prost(
        enumeration = "super::super::super::common::v1::SponsoredType",
        optional,
        tag = "10"
    )]
    pub sponsorship_type: ::core::option::Option<i32>,
    /// The customer's tax registration number (e.g. VAT ID) on file.
    #[prost(string, optional, tag = "11")]
    pub tax_number: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether the tax provider placed this invoice under reverse charge.
    #[prost(bool, tag = "12")]
    pub is_reverse_charge: bool,
    /// Which arrangement bills the contract. Each arrangement carries only the
    /// configuration that applies to it. Unset defaults to credit-card.
    #[prost(oneof = "create_contract_request::Billing", tags = "7, 8, 13")]
    pub billing: ::core::option::Option<create_contract_request::Billing>,
}
/// Nested message and enum types in `CreateContractRequest`.
pub mod create_contract_request {
    /// Which arrangement bills the contract. Each arrangement carries only the
    /// configuration that applies to it. Unset defaults to credit-card.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Billing {
        #[prost(message, tag = "7")]
        CreditCard(super::CreditCardConfig),
        #[prost(message, tag = "8")]
        Invoiced(super::InvoicedConfig),
        #[prost(message, tag = "13")]
        Partner(super::PartnerConfig),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateContractResponse {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub invoice_id: u64,
    #[prost(string, tag = "3")]
    pub invoice_guid: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub needs_charge: bool,
    #[prost(uint64, tag = "5")]
    pub amount_billed: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAllContractsForOrganizationRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllContractsForOrganizationResponse {
    #[prost(message, repeated, tag = "1")]
    pub contracts: ::prost::alloc::vec::Vec<Contract>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetContractRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    /// If provided, returns the Contract active on this date. Otherwise, returns the current Contract.
    #[prost(message, optional, tag = "2")]
    pub date: ::core::option::Option<super::super::super::Date>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSpecificContractRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetContractResponse {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Contract>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUninvoicedContractsRequest {
    /// Returns Contracts whose current billing period ends before this time and
    /// have not yet been invoiced for the current period.
    #[prost(message, optional, tag = "1")]
    pub current_ts: ::core::option::Option<::prost_types::Timestamp>,
    /// Maximum number of contracts to return in the response. If more contracts
    /// match the request than this limit, the response will have truncated set
    /// to true.
    #[prost(uint32, tag = "2")]
    pub max_items: u32,
    #[prost(uint32, optional, tag = "3")]
    pub offset: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUninvoicedContractsResponse {
    /// True if additional matching contracts existed beyond max_items and were
    /// not included in this response.
    #[prost(bool, tag = "1")]
    pub truncated: bool,
    #[prost(uint64, repeated, tag = "2")]
    pub contract_ids: ::prost::alloc::vec::Vec<u64>,
}
