// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub postal_code: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub address_line_1: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub address_line_2: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub address_line_3: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingDetails {
    #[deprecated]
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Address>,
    #[prost(string, tag = "2")]
    pub display_address: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub company_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub billing_email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub billing_address: ::core::option::Option<
        super::super::super::common::v1::Address,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBillingDetailsRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBillingDetailsResponse {
    #[prost(message, optional, tag = "1")]
    pub billing_details: ::core::option::Option<BillingDetails>,
}
/// Fetches lightweight identity fields for an organization. Used by callers
/// that need slug/name/default_user_id without pulling the full Organization
/// record across service boundaries.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrganizationMetadataRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrganizationMetadataResponse {
    #[prost(string, tag = "1")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Unset when the organization has no default owner.
    #[prost(uint64, optional, tag = "3")]
    pub default_user_id: ::core::option::Option<u64>,
    /// Email of the default owner.
    #[prost(string, optional, tag = "4")]
    pub default_owner_email: ::core::option::Option<::prost::alloc::string::String>,
    /// Emails of every active org member whose role grants the "org:billing"
    /// scope (e.g. owner, manager, billing).
    #[prost(string, repeated, tag = "5")]
    pub billing_role_emails: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStripePaymentDataRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStripePaymentDataResponse {
    #[prost(message, optional, tag = "1")]
    pub stripe_payment_data: ::core::option::Option<
        super::super::super::common::v1::StripePaymentData,
    >,
}
