// This file is @generated by prost-build.
/// Per-project seat usage over a date range, used by get_daily_seat_usage_by_project.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectSeatUsage {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub seat_days: ::prost::alloc::vec::Vec<super::super::usage::v1::DailySeatUsage>,
}
/// Result of a seat assignment or check_assign_seats call.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SeatAssignmentOutcome {
    Unspecified = 0,
    /// Seat fits within reserved or PAYG capacity.
    Accepted = 1,
    /// No budget remaining; seat is created as OVER_QUOTA on assign.
    RateLimited = 2,
    /// Product not enabled on plan or request is structurally invalid.
    Invalid = 3,
}
impl SeatAssignmentOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEAT_ASSIGNMENT_OUTCOME_UNSPECIFIED",
            Self::Accepted => "SEAT_ASSIGNMENT_OUTCOME_ACCEPTED",
            Self::RateLimited => "SEAT_ASSIGNMENT_OUTCOME_RATE_LIMITED",
            Self::Invalid => "SEAT_ASSIGNMENT_OUTCOME_INVALID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEAT_ASSIGNMENT_OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "SEAT_ASSIGNMENT_OUTCOME_ACCEPTED" => Some(Self::Accepted),
            "SEAT_ASSIGNMENT_OUTCOME_RATE_LIMITED" => Some(Self::RateLimited),
            "SEAT_ASSIGNMENT_OUTCOME_INVALID" => Some(Self::Invalid),
            _ => None,
        }
    }
}
/// Assigns a single billing seat for the current contract period. Internally
/// runs check_assign_seats to determine capacity: ACCEPTED seats become ACTIVE,
/// RATE_LIMITED seats become OVER_QUOTA, INVALID seats are rejected.
/// Lazily initializes the contract's seat tracker on first write.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::seat_activity::v1::SeatObject>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignSeatResponse {
    #[prost(enumeration = "SeatAssignmentOutcome", tag = "1")]
    pub outcome: i32,
}
/// Dry-run check: can these seats be assigned? Validates the product is enabled
/// on the plan, filters out already-existing seats, then simulates usage pricing
/// to determine if reserved or PAYG budgets have capacity.
/// All seat_objects must share the same seat category and organization.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckAssignSeatsRequest {
    #[prost(message, repeated, tag = "1")]
    pub seat_objects: ::prost::alloc::vec::Vec<
        super::super::seat_activity::v1::SeatObject,
    >,
    /// When omitted, resolves to the org's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckAssignSeatsResponse {
    #[prost(enumeration = "SeatAssignmentOutcome", tag = "1")]
    pub outcome: i32,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// Sets a seat to DISABLED status. The seat still counts toward the period
/// total but stops accepting new activity (e.g. check-ins are dropped).
/// Only allowed for seat categories whose policy supports disabling.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::seat_activity::v1::SeatObject>,
    /// When omitted, resolves to the org's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableSeatResponse {}
/// Response-only proto; the request reuses GetUsageRequest from the usage service.
/// Returns per-day billable and active seat counts for the requested period.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDailySeatUsageResponse {
    #[prost(message, repeated, tag = "1")]
    pub seat_days: ::prost::alloc::vec::Vec<super::super::usage::v1::DailySeatUsage>,
}
/// Response-only proto; the request reuses GetUsageByProjectRequest from the
/// usage service. Same as GetDailySeatUsageResponse but broken out per project.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDailySeatUsageByProjectResponse {
    #[prost(message, repeated, tag = "1")]
    pub projects: ::prost::alloc::vec::Vec<ProjectSeatUsage>,
}
/// High-throughput read path called by the monitor consumer on every check-in.
/// Looks up the seat's current state and maps it to an external-facing status.
/// OVER_QUOTA is mapped to DISABLED — external consumers do not distinguish
/// between the two.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStatusForExternalProductRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::seat_activity::v1::SeatObject>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStatusForExternalProductResponse {
    #[prost(enumeration = "super::super::super::common::v1::SeatStatus", tag = "1")]
    pub status: i32,
}
/// Permanently removes a seat (status -> DNE), freeing the slot for
/// reallocation. Only allowed for seat categories whose policy supports removal.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::seat_activity::v1::SeatObject>,
    /// When omitted, resolves to the org's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveSeatResponse {}
/// Recreates carry-over seats when a contract rolls over. Closes the old
/// contract's tracker, collects seats that ended ACTIVE or OVER_QUOTA, orders
/// them by seniority, and splits against the new contract's capacity (fits ->
/// ACTIVE, overflow -> OVER_QUOTA). No-ops if the new contract already has
/// seat state (idempotent on retry).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RolloverSeatsToNewContractRequest {
    #[prost(uint64, tag = "1")]
    pub prev_contract_id: u64,
    #[prost(uint64, tag = "2")]
    pub new_contract_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RolloverSeatsToNewContractResponse {}
/// Atomically renames a seat's identifier (e.g. when a monitor slug changes).
/// Implemented as two actions in one batch: old identifier -> DNE, new
/// identifier -> previous status. Only allowed for seat categories whose
/// policy supports renaming.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSeatIdentifierRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::seat_activity::v1::SeatObject>,
    #[prost(string, tag = "2")]
    pub new_identifier: ::prost::alloc::string::String,
    /// When omitted, resolves to the org's current contract.
    #[prost(uint64, optional, tag = "3")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSeatIdentifierResponse {}
