// This file is @generated by prost-build.
/// Invoices an immediate mid-term contract change and rolls the contract over
/// now. The caller supplies the change to apply (target package/interval and the
/// caps taking effect now). The invoicer prices the prorated new-plan charge and
/// the credit for unused time on the current plan itself, settles accrued
/// pay-as-you-go usage at the current contract's rates, applies monetary grants
/// and sales tax, closes the current contract immediately, and opens the new
/// contract with the supplied change applied.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BillContractChangeRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    /// The change applied to the new contract: the target package/interval and the
    /// PAYG caps taking effect now. Reuses the PendingChange shape the rollover
    /// consumes, but here it applies immediately rather than at a period boundary,
    /// so the caller does not stage it in the pending-change store.
    #[prost(message, optional, tag = "2")]
    pub change: ::core::option::Option<super::super::super::common::v1::PendingChange>,
    /// Whether the requested change should result in a new billing period.
    #[prost(bool, tag = "3")]
    pub start_new_term: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillContractChangeResponse {
    /// The invoice that settles the change (and closes the previous contract).
    #[prost(uint64, tag = "1")]
    pub invoice_id: u64,
}
