// This file is @generated by prost-build.
/// Estimates what a contract will use for the remainder of its on-demand
/// period, so a customer sees a full period rather than a series that stops
/// at today.
///
/// The estimate is a weighted average of the contract's recent daily usage,
/// decayed so that older days count for less. The sample reaches back into
/// prior billing periods, because a contract's own period is a poor sample on
/// its first days.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectedDailyBreakdownRequest {
    /// The contract whose remaining on-demand period should be projected.
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    /// The day the projection is made from. Days up to and including this one
    /// are sampled; days strictly after it are projected, through the
    /// contract's on-demand period end.
    #[prost(message, optional, tag = "2")]
    pub current_date: ::core::option::Option<super::super::super::Date>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectedDailyBreakdownResponse {
    /// Projected days in ascending date order, one per day between
    /// `current_date` (exclusive) and the contract's on-demand period end
    /// (inclusive). Empty when the period has already ended.
    ///
    /// The rows are deliberately the same type UsagePricer returns for actual
    /// usage, so a caller can render or concatenate actual and projected days
    /// without converting between two shapes. Every projected day repeats the
    /// same estimate, because the estimate is a single weighted average per
    /// line item rather than a per-day forecast.
    #[prost(message, repeated, tag = "1")]
    pub days: ::prost::alloc::vec::Vec<
        super::super::usage_pricer::v1::DailyLineItemOutcomes,
    >,
}
