// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountStatus {
    /// The organization this status belongs to. Each org has one AccountStatus.
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    /// Legacy soft cap flag. When true, no category is rate-limited regardless of usage.
    #[prost(bool, tag = "2")]
    pub soft_cap: bool,
    /// Current account status (active, closed, past-due).
    #[prost(enumeration = "Status", tag = "3")]
    pub status: i32,
    /// Whether the account is suspended by an admin (e.g., for fraud).
    #[prost(bool, tag = "4")]
    pub is_suspended: bool,
    /// Free-form reason for admin suspension (e.g., "fraud", "tos_violation").
    #[prost(string, tag = "5")]
    pub suspension_reason: ::prost::alloc::string::String,
    /// PAYG on-demand spending status.
    #[prost(enumeration = "OnDemandStatus", tag = "6")]
    pub ondemand_status: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unspecified = 0,
    Active = 1,
    Closed = 2,
    PastDue = 3,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_UNSPECIFIED",
            Self::Active => "STATUS_ACTIVE",
            Self::Closed => "STATUS_CLOSED",
            Self::PastDue => "STATUS_PAST_DUE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "STATUS_ACTIVE" => Some(Self::Active),
            "STATUS_CLOSED" => Some(Self::Closed),
            "STATUS_PAST_DUE" => Some(Self::PastDue),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OnDemandStatus {
    Unspecified = 0,
    Enabled = 1,
    Disabled = 2,
}
impl OnDemandStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ON_DEMAND_STATUS_UNSPECIFIED",
            Self::Enabled => "ON_DEMAND_STATUS_ENABLED",
            Self::Disabled => "ON_DEMAND_STATUS_DISABLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ON_DEMAND_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "ON_DEMAND_STATUS_ENABLED" => Some(Self::Enabled),
            "ON_DEMAND_STATUS_DISABLED" => Some(Self::Disabled),
            _ => None,
        }
    }
}
