// This file is @generated by prost-build.
/// A file changed by a coding-agent task.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangedFile {
    /// Repo-relative path of the file.
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// How the file changed.
    #[prost(enumeration = "changed_file::ChangeType", tag = "2")]
    pub change_type: i32,
    /// Full file content. Unset for deleted files.
    #[prost(string, optional, tag = "3")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `ChangedFile`.
pub mod changed_file {
    /// How the file changed relative to the base branch.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ChangeType {
        Unspecified = 0,
        Added = 1,
        Modified = 2,
        Deleted = 3,
    }
    impl ChangeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "CHANGE_TYPE_UNSPECIFIED",
                Self::Added => "CHANGE_TYPE_ADDED",
                Self::Modified => "CHANGE_TYPE_MODIFIED",
                Self::Deleted => "CHANGE_TYPE_DELETED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CHANGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "CHANGE_TYPE_ADDED" => Some(Self::Added),
                "CHANGE_TYPE_MODIFIED" => Some(Self::Modified),
                "CHANGE_TYPE_DELETED" => Some(Self::Deleted),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSandboxRequest {
    /// SandboxTemplate to instantiate. The router's default is used when unset.
    #[prost(string, optional, tag = "1")]
    pub template_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Namespace to create the sandbox in. The router's default is used when unset.
    #[prost(string, optional, tag = "2")]
    pub namespace: ::core::option::Option<::prost::alloc::string::String>,
    /// Time-to-live in seconds before the sandbox is automatically deleted. The
    /// router's default is used when unset.
    #[prost(int32, optional, tag = "3")]
    pub ttl_seconds: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSandboxResponse {
    /// Identifier for the sandbox, used to route subsequent requests to it.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// Namespace the sandbox was created in.
    #[prost(string, tag = "2")]
    pub namespace: ::prost::alloc::string::String,
    /// SandboxTemplate the sandbox was instantiated from.
    #[prost(string, tag = "3")]
    pub template_name: ::prost::alloc::string::String,
    /// When the sandbox will be automatically deleted.
    #[prost(message, optional, tag = "4")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSandboxRequest {
    /// Identifier of the sandbox to delete.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// Namespace the sandbox lives in. The router's default is used when unset.
    #[prost(string, optional, tag = "2")]
    pub namespace: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSandboxResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitCodingTaskRequest {
    /// URL of the repository to clone.
    #[prost(string, tag = "1")]
    pub repo_url: ::prost::alloc::string::String,
    /// Branch the agent should create and push its work to.
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
    /// Natural-language description of the issue for the agent to work on.
    #[prost(string, tag = "3")]
    pub issue_description: ::prost::alloc::string::String,
    /// Branch to base the work on.
    #[prost(string, tag = "4")]
    pub base_branch: ::prost::alloc::string::String,
    /// Short-lived token used to clone a private repository. Unset for public repos.
    #[prost(string, optional, tag = "5")]
    pub repo_access_token: ::core::option::Option<::prost::alloc::string::String>,
    /// Commands to set up the environment, overriding auto-detection.
    #[prost(string, repeated, tag = "6")]
    pub setup_commands: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Time-to-live in seconds for the underlying sandbox. The router's default is
    /// used when unset.
    #[prost(int32, optional, tag = "7")]
    pub ttl_seconds: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitCodingTaskResponse {
    /// Identifier for the submitted task, used to poll for its result.
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// Status of the task at submission time.
    #[prost(enumeration = "CodingTaskStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCodingTaskRequest {
    /// Identifier of the task to fetch.
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCodingTaskResponse {
    /// The current state and result of the task.
    #[prost(message, optional, tag = "1")]
    pub task: ::core::option::Option<CodingTask>,
}
/// The state and result of a coding-agent task.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodingTask {
    /// Identifier of the task.
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// Current lifecycle status of the task.
    #[prost(enumeration = "CodingTaskStatus", tag = "2")]
    pub status: i32,
    /// Phase the task is in while running.
    #[prost(enumeration = "CodingTaskPhase", tag = "3")]
    pub phase: i32,
    /// Identifier of the sandbox running the task.
    #[prost(string, tag = "4")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// Agent-produced summary of the work done.
    #[prost(string, tag = "5")]
    pub summary: ::prost::alloc::string::String,
    /// Unified diff of the changes, for display and review.
    #[prost(string, tag = "6")]
    pub diff: ::prost::alloc::string::String,
    /// Full contents of the changed files, for applying via the GitHub API.
    #[prost(message, repeated, tag = "7")]
    pub files_changed: ::prost::alloc::vec::Vec<ChangedFile>,
    /// Branch the agent pushed its work to.
    #[prost(string, tag = "8")]
    pub git_branch: ::prost::alloc::string::String,
    /// Number of commits the agent made.
    #[prost(int32, tag = "9")]
    pub commit_count: i32,
    /// Error message when the task failed.
    #[prost(string, tag = "10")]
    pub error: ::prost::alloc::string::String,
    /// When the task was created.
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// When the task finished. Unset while the task is still running.
    #[prost(message, optional, tag = "12")]
    pub completed_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelCodingTaskRequest {
    /// Identifier of the task to cancel.
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelCodingTaskResponse {
    /// Identifier of the cancelled task.
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// Status of the task after cancellation.
    #[prost(enumeration = "CodingTaskStatus", tag = "2")]
    pub status: i32,
}
/// The lifecycle status of a coding-agent task.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CodingTaskStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Success = 3,
    Error = 4,
}
impl CodingTaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CODING_TASK_STATUS_UNSPECIFIED",
            Self::Pending => "CODING_TASK_STATUS_PENDING",
            Self::Running => "CODING_TASK_STATUS_RUNNING",
            Self::Success => "CODING_TASK_STATUS_SUCCESS",
            Self::Error => "CODING_TASK_STATUS_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CODING_TASK_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CODING_TASK_STATUS_PENDING" => Some(Self::Pending),
            "CODING_TASK_STATUS_RUNNING" => Some(Self::Running),
            "CODING_TASK_STATUS_SUCCESS" => Some(Self::Success),
            "CODING_TASK_STATUS_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
/// The phase a running coding-agent task is currently in.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CodingTaskPhase {
    Unspecified = 0,
    Setup = 1,
    Execution = 2,
    Completion = 3,
}
impl CodingTaskPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CODING_TASK_PHASE_UNSPECIFIED",
            Self::Setup => "CODING_TASK_PHASE_SETUP",
            Self::Execution => "CODING_TASK_PHASE_EXECUTION",
            Self::Completion => "CODING_TASK_PHASE_COMPLETION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CODING_TASK_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "CODING_TASK_PHASE_SETUP" => Some(Self::Setup),
            "CODING_TASK_PHASE_EXECUTION" => Some(Self::Execution),
            "CODING_TASK_PHASE_COMPLETION" => Some(Self::Completion),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sandbox_router_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SandboxRouterService orchestrates ephemeral sandbox pods that run AI coding
    /// agents on customer repositories.
    #[derive(Debug, Clone)]
    pub struct SandboxRouterServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SandboxRouterServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SandboxRouterServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SandboxRouterServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SandboxRouterServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// CreateSandbox provisions a sandbox and waits for it to become ready.
        pub async fn create_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CreateSandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "CreateSandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DeleteSandbox tears down a sandbox and its resources.
        pub async fn delete_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/DeleteSandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "DeleteSandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// SubmitCodingTask starts a coding-agent task and returns immediately with a
        /// task identifier to poll.
        pub async fn submit_coding_task(
            &mut self,
            request: impl tonic::IntoRequest<super::SubmitCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitCodingTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/SubmitCodingTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "SubmitCodingTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetCodingTask returns the current state and result of a coding-agent task.
        pub async fn get_coding_task(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCodingTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/GetCodingTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "GetCodingTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// CancelCodingTask cancels a running coding-agent task and cleans up its
        /// sandbox.
        pub async fn cancel_coding_task(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelCodingTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CancelCodingTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SandboxRouterService",
                        "CancelCodingTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod sandbox_router_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SandboxRouterServiceServer.
    #[async_trait]
    pub trait SandboxRouterService: std::marker::Send + std::marker::Sync + 'static {
        /// CreateSandbox provisions a sandbox and waits for it to become ready.
        async fn create_sandbox(
            &self,
            request: tonic::Request<super::CreateSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSandboxResponse>,
            tonic::Status,
        >;
        /// DeleteSandbox tears down a sandbox and its resources.
        async fn delete_sandbox(
            &self,
            request: tonic::Request<super::DeleteSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSandboxResponse>,
            tonic::Status,
        >;
        /// SubmitCodingTask starts a coding-agent task and returns immediately with a
        /// task identifier to poll.
        async fn submit_coding_task(
            &self,
            request: tonic::Request<super::SubmitCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitCodingTaskResponse>,
            tonic::Status,
        >;
        /// GetCodingTask returns the current state and result of a coding-agent task.
        async fn get_coding_task(
            &self,
            request: tonic::Request<super::GetCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCodingTaskResponse>,
            tonic::Status,
        >;
        /// CancelCodingTask cancels a running coding-agent task and cleans up its
        /// sandbox.
        async fn cancel_coding_task(
            &self,
            request: tonic::Request<super::CancelCodingTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelCodingTaskResponse>,
            tonic::Status,
        >;
    }
    /// SandboxRouterService orchestrates ephemeral sandbox pods that run AI coding
    /// agents on customer repositories.
    #[derive(Debug)]
    pub struct SandboxRouterServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SandboxRouterServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for SandboxRouterServiceServer<T>
    where
        T: SandboxRouterService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CreateSandbox" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSandboxSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::CreateSandboxRequest>
                    for CreateSandboxSvc<T> {
                        type Response = super::CreateSandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateSandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::create_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/DeleteSandbox" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSandboxSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::DeleteSandboxRequest>
                    for DeleteSandboxSvc<T> {
                        type Response = super::DeleteSandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteSandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::delete_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/SubmitCodingTask" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitCodingTaskSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::SubmitCodingTaskRequest>
                    for SubmitCodingTaskSvc<T> {
                        type Response = super::SubmitCodingTaskResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubmitCodingTaskRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::submit_coding_task(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitCodingTaskSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/GetCodingTask" => {
                    #[allow(non_camel_case_types)]
                    struct GetCodingTaskSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::GetCodingTaskRequest>
                    for GetCodingTaskSvc<T> {
                        type Response = super::GetCodingTaskResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCodingTaskRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::get_coding_task(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCodingTaskSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.seer.v2alpha.SandboxRouterService/CancelCodingTask" => {
                    #[allow(non_camel_case_types)]
                    struct CancelCodingTaskSvc<T: SandboxRouterService>(pub Arc<T>);
                    impl<
                        T: SandboxRouterService,
                    > tonic::server::UnaryService<super::CancelCodingTaskRequest>
                    for CancelCodingTaskSvc<T> {
                        type Response = super::CancelCodingTaskResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelCodingTaskRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxRouterService>::cancel_coding_task(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelCodingTaskSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SandboxRouterServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.seer.v2alpha.SandboxRouterService";
    impl<T> tonic::server::NamedService for SandboxRouterServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// A model that Seer can use to serve requests.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Model {
    /// The provider-facing model name. This is the identifier used to request
    /// the model, e.g. "claude-opus-4-8@default" or "gemini-2.5-pro".
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The provider that serves the model.
    #[prost(enumeration = "Provider", tag = "2")]
    pub provider: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModelsResponse {
    /// The models currently available to Seer.
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<Model>,
}
/// The provider that serves a model. Mirrors Seer's LlmProviderType.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Provider {
    Unspecified = 0,
    Openai = 1,
    Anthropic = 2,
    Gemini = 3,
}
impl Provider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROVIDER_UNSPECIFIED",
            Self::Openai => "PROVIDER_OPENAI",
            Self::Anthropic => "PROVIDER_ANTHROPIC",
            Self::Gemini => "PROVIDER_GEMINI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "PROVIDER_OPENAI" => Some(Self::Openai),
            "PROVIDER_ANTHROPIC" => Some(Self::Anthropic),
            "PROVIDER_GEMINI" => Some(Self::Gemini),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod seer_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SeerService exposes Seer's capabilities over RPC.
    #[derive(Debug, Clone)]
    pub struct SeerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SeerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SeerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SeerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SeerServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetModels returns the models currently available to Seer.
        pub async fn get_models(
            &mut self,
            request: impl tonic::IntoRequest<super::GetModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.seer.v2alpha.SeerService/GetModels",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.seer.v2alpha.SeerService",
                        "GetModels",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod seer_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SeerServiceServer.
    #[async_trait]
    pub trait SeerService: std::marker::Send + std::marker::Sync + 'static {
        /// GetModels returns the models currently available to Seer.
        async fn get_models(
            &self,
            request: tonic::Request<super::GetModelsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetModelsResponse>,
            tonic::Status,
        >;
    }
    /// SeerService exposes Seer's capabilities over RPC.
    #[derive(Debug)]
    pub struct SeerServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SeerServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SeerServiceServer<T>
    where
        T: SeerService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.seer.v2alpha.SeerService/GetModels" => {
                    #[allow(non_camel_case_types)]
                    struct GetModelsSvc<T: SeerService>(pub Arc<T>);
                    impl<
                        T: SeerService,
                    > tonic::server::UnaryService<super::GetModelsRequest>
                    for GetModelsSvc<T> {
                        type Response = super::GetModelsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetModelsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SeerService>::get_models(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetModelsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SeerServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.seer.v2alpha.SeerService";
    impl<T> tonic::server::NamedService for SeerServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
