// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub postal_code: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub address_line_1: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub address_line_2: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub address_line_3: ::prost::alloc::string::String,
}
/// Defines how usage data is transformed into a billable line item through arithmetic operations.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BillableMetric {
    /// Unique identifier for the billable metric.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Name of the billable metric (e.g., "performance_units").
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Expression defining how to calculate this metric from usage data.
    #[prost(message, optional, tag = "3")]
    pub expression: ::core::option::Option<Expression>,
}
/// Represents an arithmetic expression that can reference usage data categories or constants.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expression {
    #[prost(oneof = "expression::ExpressionType", tags = "1, 2, 3")]
    pub expression_type: ::core::option::Option<expression::ExpressionType>,
}
/// Nested message and enum types in `Expression`.
pub mod expression {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ExpressionType {
        /// Reference to a data category's usage count.
        #[prost(message, tag = "1")]
        CategoryRef(super::CategoryReference),
        /// A constant numeric value.
        #[prost(double, tag = "2")]
        Constant(f64),
        /// A binary arithmetic operation.
        #[prost(message, tag = "3")]
        BinaryOp(::prost::alloc::boxed::Box<super::BinaryOperation>),
    }
}
/// Reference to a usage data category.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CategoryReference {
    #[prost(oneof = "category_reference::CategoryType", tags = "1, 2")]
    pub category_type: ::core::option::Option<category_reference::CategoryType>,
}
/// Nested message and enum types in `CategoryReference`.
pub mod category_reference {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum CategoryType {
        #[prost(enumeration = "super::super::super::DataCategory", tag = "1")]
        DataCategory(i32),
        #[prost(enumeration = "super::super::super::SeatCategory", tag = "2")]
        SeatCategory(i32),
    }
}
/// A binary arithmetic operation between two expressions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BinaryOperation {
    /// The operator to apply.
    #[prost(enumeration = "Operator", tag = "1")]
    pub operator: i32,
    /// Left operand.
    #[prost(message, optional, boxed, tag = "2")]
    pub left: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    /// Right operand.
    #[prost(message, optional, boxed, tag = "3")]
    pub right: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
}
/// Supported arithmetic operators.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Operator {
    Unspecified = 0,
    /// *
    Add = 1,
    /// *
    Subtract = 2,
    /// *
    Multiply = 3,
    /// /
    Divide = 4,
}
impl Operator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPERATOR_UNSPECIFIED",
            Self::Add => "OPERATOR_ADD",
            Self::Subtract => "OPERATOR_SUBTRACT",
            Self::Multiply => "OPERATOR_MULTIPLY",
            Self::Divide => "OPERATOR_DIVIDE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATOR_UNSPECIFIED" => Some(Self::Unspecified),
            "OPERATOR_ADD" => Some(Self::Add),
            "OPERATOR_SUBTRACT" => Some(Self::Subtract),
            "OPERATOR_MULTIPLY" => Some(Self::Multiply),
            "OPERATOR_DIVIDE" => Some(Self::Divide),
            _ => None,
        }
    }
}
/// Billing interval for packages and contracts.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingInterval {
    Unspecified = 0,
    Monthly = 1,
    AnnualBaseMonthlyPayg = 2,
}
impl BillingInterval {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_INTERVAL_UNSPECIFIED",
            Self::Monthly => "BILLING_INTERVAL_MONTHLY",
            Self::AnnualBaseMonthlyPayg => "BILLING_INTERVAL_ANNUAL_BASE_MONTHLY_PAYG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_INTERVAL_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_INTERVAL_MONTHLY" => Some(Self::Monthly),
            "BILLING_INTERVAL_ANNUAL_BASE_MONTHLY_PAYG" => {
                Some(Self::AnnualBaseMonthlyPayg)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlexiblePrice {
    #[prost(uint64, tag = "1")]
    pub base: u64,
    #[prost(oneof = "flexible_price::AnnualPrice", tags = "2")]
    pub annual_price: ::core::option::Option<flexible_price::AnnualPrice>,
}
/// Nested message and enum types in `FlexiblePrice`.
pub mod flexible_price {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum AnnualPrice {
        #[prost(uint64, tag = "2")]
        Fixed(u64),
    }
}
/// Unit information for measurement and conversion.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnitInfo {
    /// Short name for the unit (e.g., "GB", "cm", "count").
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Full descriptive name (e.g., "gigabytes", "centimeters", "count").
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    /// Base unit for conversion.
    #[prost(enumeration = "BaseUnit", tag = "3")]
    pub base_unit: i32,
    /// Multiplier to convert to base unit (e.g., 1e9 for GB to bytes).
    #[prost(double, tag = "4")]
    pub multiplier: f64,
}
/// Base unit types for measurement and conversion.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BaseUnit {
    Unspecified = 0,
    Byte = 1,
    Count = 2,
    Second = 3,
    Millisecond = 4,
}
impl BaseUnit {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BASE_UNIT_UNSPECIFIED",
            Self::Byte => "BASE_UNIT_BYTE",
            Self::Count => "BASE_UNIT_COUNT",
            Self::Second => "BASE_UNIT_SECOND",
            Self::Millisecond => "BASE_UNIT_MILLISECOND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BASE_UNIT_UNSPECIFIED" => Some(Self::Unspecified),
            "BASE_UNIT_BYTE" => Some(Self::Byte),
            "BASE_UNIT_COUNT" => Some(Self::Count),
            "BASE_UNIT_SECOND" => Some(Self::Second),
            "BASE_UNIT_MILLISECOND" => Some(Self::Millisecond),
            _ => None,
        }
    }
}
/// Details of a SKU line item in the billing system.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineItemDetails {
    /// Unique identifier for the line item.
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// Customer-facing display name for the line item.
    #[prost(string, tag = "3")]
    pub customer_facing_name: ::prost::alloc::string::String,
    /// Plural form of the customer-facing name.
    #[prost(string, tag = "4")]
    pub plural: ::prost::alloc::string::String,
    /// Unit information for measurement.
    #[prost(message, optional, tag = "5")]
    pub units: ::core::option::Option<UnitInfo>,
    /// Defines how usage data is transformed into this line item.
    #[prost(message, optional, tag = "6")]
    pub billable_metric: ::core::option::Option<BillableMetric>,
    /// DEPRECATED: do not use. The getsentry DataCategory value this line item
    /// bills (the unified getsentry/sentry DataCategory int, NOT the proto
    /// sentry_protos.billing.v1.DataCategory enum). Exists only to support legacy
    /// code that hardcodes category values during the billing-platform migration.
    /// New line items must be addable, and new consumers written, without anyone
    /// hardcoding or reading a category off the line item.
    #[deprecated]
    #[prost(int32, tag = "7")]
    pub line_item_category: i32,
}
/// Stripe-specific payment information for an organization.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StripePaymentData {
    #[prost(string, optional, tag = "1")]
    pub customer_stripe_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub default_payment_method_id: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    #[prost(bool, optional, tag = "3")]
    pub has_card_on_file: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "4")]
    pub last4: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub postal_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub country_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "7")]
    pub exp_month: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "8")]
    pub exp_year: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "9")]
    pub brand: ::core::option::Option<::prost::alloc::string::String>,
}
/// Payment provider configuration with support for multiple providers.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentConfig {
    #[prost(oneof = "payment_config::Config", tags = "1")]
    pub config: ::core::option::Option<payment_config::Config>,
}
/// Nested message and enum types in `PaymentConfig`.
pub mod payment_config {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Config {
        /// Future payment providers (e.g., PayPal, Braintree) can be added here
        #[prost(message, tag = "1")]
        Stripe(super::StripePaymentData),
    }
}
/// The type of sponsorship associated with a contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SponsoredType {
    Unspecified = 0,
    Education = 1,
    OpenSource = 2,
    NonProfit = 3,
    FriendsAndFamily = 4,
    FlyIo = 5,
    Nintendo = 6,
    Employee = 7,
}
impl SponsoredType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SPONSORED_TYPE_UNSPECIFIED",
            Self::Education => "SPONSORED_TYPE_EDUCATION",
            Self::OpenSource => "SPONSORED_TYPE_OPEN_SOURCE",
            Self::NonProfit => "SPONSORED_TYPE_NON_PROFIT",
            Self::FriendsAndFamily => "SPONSORED_TYPE_FRIENDS_AND_FAMILY",
            Self::FlyIo => "SPONSORED_TYPE_FLY_IO",
            Self::Nintendo => "SPONSORED_TYPE_NINTENDO",
            Self::Employee => "SPONSORED_TYPE_EMPLOYEE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SPONSORED_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SPONSORED_TYPE_EDUCATION" => Some(Self::Education),
            "SPONSORED_TYPE_OPEN_SOURCE" => Some(Self::OpenSource),
            "SPONSORED_TYPE_NON_PROFIT" => Some(Self::NonProfit),
            "SPONSORED_TYPE_FRIENDS_AND_FAMILY" => Some(Self::FriendsAndFamily),
            "SPONSORED_TYPE_FLY_IO" => Some(Self::FlyIo),
            "SPONSORED_TYPE_NINTENDO" => Some(Self::Nintendo),
            "SPONSORED_TYPE_EMPLOYEE" => Some(Self::Employee),
            _ => None,
        }
    }
}
/// A pending change is a deferred subscription change for an organization that
/// will apply at the next billing period rollover. Each org has at most one
/// pending change at a time. Any field left unset means that aspect of the
/// subscription is not being changed.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PendingChange {
    /// The package the subscription will switch to. Unset means the package is
    /// not changing.
    #[prost(string, optional, tag = "1")]
    pub package_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Pending PAYG-budget and reservation overrides, grouped by the set of line
    /// items they apply to. This mirrors the UserConfig shape used by the
    /// contract pricing config: each entry describes a line-item subset (or "all
    /// line items") together with its pending PAYG budget and/or reservation.
    /// Shared reserved-budget pools (e.g. Seer covering autofix + scanner +
    /// users) are represented as a single PendingUserConfig that lists every
    /// line item in the pool.
    #[prost(message, repeated, tag = "2")]
    pub user_configs: ::prost::alloc::vec::Vec<PendingUserConfig>,
    /// New contract month_interval. Used for downgrades from annual to monthly
    #[prost(uint32, optional, tag = "3")]
    pub month_interval: ::core::option::Option<u32>,
    /// Next contract's sponsored_type. SPONSORED_TYPE_UNSPECIFIED clears the
    /// sponsorship; an unset field leaves it unchanged.
    #[prost(enumeration = "SponsoredType", optional, tag = "4")]
    pub sponsored_type: ::core::option::Option<i32>,
}
/// Pending overrides for a set of line items. payg_budget and reservation are
/// each independently optional - either, both, or neither may be set on a
/// given config.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingUserConfig {
    /// Pending PAYG budget for the covered line items. Unset means the PAYG
    /// budget is not changing.
    #[prost(message, optional, tag = "1")]
    pub payg_budget: ::core::option::Option<PaygBudget>,
    /// Pending reservation (price and unit count) for the covered line items.
    /// Unset means the reservation is not changing.
    #[prost(message, optional, tag = "2")]
    pub reservation: ::core::option::Option<Reservation>,
    /// The line items this config applies to.
    #[prost(oneof = "pending_user_config::LineItems", tags = "3, 4")]
    pub line_items: ::core::option::Option<pending_user_config::LineItems>,
}
/// Nested message and enum types in `PendingUserConfig`.
pub mod pending_user_config {
    /// The line items this config applies to.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum LineItems {
        /// Explicit list of line item uids (e.g. one line item, or multiple line
        /// items that share a reserved-budget pool).
        #[prost(message, tag = "3")]
        SpecificItems(super::LineItemUids),
        /// Sentinel meaning "all line items on the package." Used for top-level
        /// shared PAYG budgets.
        #[prost(message, tag = "4")]
        AllItems(()),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaygBudget {
    #[prost(uint64, tag = "1")]
    pub budget_cents: u64,
    /// Whether the next billing cycle should clear the Contract's existing UserParameter
    #[prost(bool, tag = "2")]
    pub clear_user_parameter: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reservation {
    #[prost(uint64, tag = "1")]
    pub reserved_price_cents: u64,
    /// Whether the next billing cycle should clear the Contract's existing UserParameter
    #[prost(bool, tag = "4")]
    pub clear_user_parameter: bool,
    #[prost(oneof = "reservation::ReservedUnits", tags = "2, 3")]
    pub reserved_units: ::core::option::Option<reservation::ReservedUnits>,
}
/// Nested message and enum types in `Reservation`.
pub mod reservation {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ReservedUnits {
        #[prost(bool, tag = "2")]
        IsUnlimited(bool),
        #[prost(uint64, tag = "3")]
        NumReservedUnits(u64),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LineItemUids {
    #[prost(string, repeated, tag = "1")]
    pub uids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingTier {
    #[prost(int64, tag = "1")]
    pub start: i64,
    #[deprecated]
    #[prost(int64, tag = "2")]
    pub end: i64,
    #[deprecated]
    #[prost(int64, tag = "3")]
    pub rate_per_unit_cpe: i64,
    #[prost(message, optional, tag = "4")]
    pub price: ::core::option::Option<FlexiblePrice>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TieredPricingRate {
    #[prost(message, repeated, tag = "1")]
    pub tiers: ::prost::alloc::vec::Vec<PricingTier>,
}
/// The complete retention settings for a data category.
///
/// These are complete package/common settings, not sparse override semantics.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetentionSettings {
    /// Standard/full-fidelity retention in calendar days. Must be greater than zero.
    #[prost(uint32, tag = "1")]
    pub standard_days: u32,
    /// Retention for a distinct downsampled representation in calendar days.
    ///
    /// Absence means the category has no distinct downsampled representation. A
    /// present zero is a package compatibility value interpreted by the retention
    /// resolver as the effective standard retention. A positive value is a
    /// concrete downsampled retention duration.
    #[prost(uint32, optional, tag = "2")]
    pub downsampled_days: ::core::option::Option<u32>,
}
/// Associates complete retention settings with a billing data category.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DataCategoryRetention {
    /// The supported billing data category. DATA_CATEGORY_UNSPECIFIED and
    /// DATA_CATEGORY_UNKNOWN are invalid.
    #[prost(enumeration = "super::super::DataCategory", tag = "1")]
    pub category: i32,
    /// The category's retention settings. Required by the domain model.
    #[prost(message, optional, tag = "2")]
    pub settings: ::core::option::Option<RetentionSettings>,
}
/// Card payment method details.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Card {
    #[prost(string, tag = "1")]
    pub last_4: ::prost::alloc::string::String,
}
/// Provider-specific payment method information attached to a charge.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentMethodDetails {
    #[prost(oneof = "payment_method_details::Details", tags = "1")]
    pub details: ::core::option::Option<payment_method_details::Details>,
}
/// Nested message and enum types in `PaymentMethodDetails`.
pub mod payment_method_details {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Details {
        #[prost(message, tag = "1")]
        Card(super::Card),
    }
}
/// A snapshot of a single Stripe refund attached to a charge. Conveys
/// per-refund metadata so handlers can record refunds individually and
/// dedupe by `id`; the aggregate `amount_refunded` on `StripeCharge`
/// alone is not enough for idempotent ingestion.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StripeRefund {
    /// Stripe id of the refund (e.g. "re_xxx").
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Refund amount in the charge's smallest currency unit (cents for USD).
    #[prost(uint64, tag = "2")]
    pub amount: u64,
    /// Stripe-supplied reason (e.g. "requested_by_customer", "duplicate",
    /// "fraudulent"). Unset when Stripe did not provide one.
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// A snapshot of a Stripe charge object. Used as the payload when reacting
/// to Stripe webhook events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StripeCharge {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub amount: u64,
    #[prost(bool, tag = "3")]
    pub refunded: bool,
    #[prost(bool, tag = "4")]
    pub paid: bool,
    #[prost(uint64, tag = "5")]
    pub amount_refunded: u64,
    /// Stripe's "created" field, expressed as Unix epoch seconds.
    #[prost(int64, tag = "6")]
    pub created_st: i64,
    #[prost(string, optional, tag = "7")]
    pub failure_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "8")]
    pub payment_method_details: ::core::option::Option<PaymentMethodDetails>,
    /// Per-refund records attached to this charge. Empty when the charge has
    /// no refunds. The list reflects the state of refunds at the time the
    /// webhook was emitted.
    #[prost(message, repeated, tag = "9")]
    pub refunds: ::prost::alloc::vec::Vec<StripeRefund>,
}
