// This file is @generated by prost-build.
/// Invalidates the contract-scoped Django cache entry used by GetQuotas for the
/// organization's current contract. Best-effort: a missing contract or lookup
/// failure is a no-op so callers can still schedule Relay project-config
/// refresh.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BustQuotasCacheRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BustQuotasCacheResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetQuotasRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(uint64, tag = "2")]
    pub project_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetQuotasResponse {
    #[prost(message, repeated, tag = "1")]
    pub quotas: ::prost::alloc::vec::Vec<super::super::super::QuotaConfig>,
    #[prost(bool, tag = "2")]
    pub contract_present: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRetentionsRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
/// An organization's resolved effective retention: the package defaults with the
/// contract's organization-wide and per-category overrides applied. Effective
/// values are computed on read and never persisted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRetentionsResponse {
    /// The per-category resolved retention. There is one entry for each category
    /// the organization's package publishes a default for. Each entry is fully
    /// resolved to concrete days: the resolver has already applied the package
    /// defaults, the sparse contract overrides, and the inherit-standard sentinel.
    /// A resolved entry never carries the sentinel value.
    #[prost(message, repeated, tag = "1")]
    pub retentions: ::prost::alloc::vec::Vec<
        super::super::super::common::v1::DataCategoryRetention,
    >,
    /// False when the organization has no platform contract, in which case consumers
    /// fall back to legacy and the remaining fields are unset.
    #[prost(bool, tag = "2")]
    pub contract_present: bool,
    /// Category-less standard retention, preserving the legacy organization-level
    /// retention call. Positive when a contract is present.
    #[prost(uint32, tag = "4")]
    pub event_retention_days: u32,
    /// Category-less downsampled retention, preserving the legacy organization-level
    /// downsampled call. Positive when a contract is present.
    #[prost(uint32, tag = "5")]
    pub downsampled_event_retention_days: u32,
}
