// This file is @generated by prost-build.
/// The outcome of a seat assignment check.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SeatOutcome {
    /// Default / unspecified.
    Unspecified = 0,
    /// The seat(s) can be assigned — budget is available.
    Accepted = 1,
    /// The seat category is not available on the current plan.
    Invalid = 2,
    /// The plan includes the category but all budget is exhausted.
    RateLimited = 3,
}
impl SeatOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEAT_OUTCOME_UNSPECIFIED",
            Self::Accepted => "SEAT_OUTCOME_ACCEPTED",
            Self::Invalid => "SEAT_OUTCOME_INVALID",
            Self::RateLimited => "SEAT_OUTCOME_RATE_LIMITED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEAT_OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "SEAT_OUTCOME_ACCEPTED" => Some(Self::Accepted),
            "SEAT_OUTCOME_INVALID" => Some(Self::Invalid),
            "SEAT_OUTCOME_RATE_LIMITED" => Some(Self::RateLimited),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::super::common::v1::SeatObject>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignSeatResponse {
    #[prost(enumeration = "SeatOutcome", tag = "1")]
    pub outcome: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckAssignSeatsRequest {
    #[prost(message, repeated, tag = "1")]
    pub seat_objects: ::prost::alloc::vec::Vec<
        super::super::super::common::v1::SeatObject,
    >,
    /// When omitted the service resolves the organization's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckAssignSeatsResponse {
    #[prost(enumeration = "SeatOutcome", tag = "1")]
    pub outcome: i32,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::super::common::v1::SeatObject>,
    /// When omitted the service resolves the organization's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
/// Seat usage for a single project.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectSeatUsage {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub seat_days: ::prost::alloc::vec::Vec<super::super::usage::v1::DailySeatUsage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDailySeatUsageByProjectResponse {
    #[prost(message, repeated, tag = "1")]
    pub projects: ::prost::alloc::vec::Vec<ProjectSeatUsage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStatusForExternalProductRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::super::common::v1::SeatObject>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSeatStatusForExternalProductResponse {
    #[prost(enumeration = "ExternalProductSeatStatus", tag = "1")]
    pub status: i32,
}
/// The status of a seat object from the perspective of the external product
/// that owns it (monitor, uptime detector, seer contributor).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExternalProductSeatStatus {
    Unspecified = 0,
    /// Does not exist, either because it was removed or it was never created.
    Dne = 1,
    /// Alive and well.
    Active = 2,
    /// The billing platform deems this seat object unusable for billing reasons.
    Disabled = 3,
}
impl ExternalProductSeatStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXTERNAL_PRODUCT_SEAT_STATUS_UNSPECIFIED",
            Self::Dne => "EXTERNAL_PRODUCT_SEAT_STATUS_DNE",
            Self::Active => "EXTERNAL_PRODUCT_SEAT_STATUS_ACTIVE",
            Self::Disabled => "EXTERNAL_PRODUCT_SEAT_STATUS_DISABLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXTERNAL_PRODUCT_SEAT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EXTERNAL_PRODUCT_SEAT_STATUS_DNE" => Some(Self::Dne),
            "EXTERNAL_PRODUCT_SEAT_STATUS_ACTIVE" => Some(Self::Active),
            "EXTERNAL_PRODUCT_SEAT_STATUS_DISABLED" => Some(Self::Disabled),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveSeatRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::super::common::v1::SeatObject>,
    /// When omitted the service resolves the organization's current contract.
    #[prost(uint64, optional, tag = "2")]
    pub contract_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RolloverSeatsToNewContractRequest {
    #[prost(uint64, tag = "1")]
    pub prev_contract_id: u64,
    #[prost(uint64, tag = "2")]
    pub new_contract_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSeatIdentifierRequest {
    #[prost(message, optional, tag = "1")]
    pub seat_object: ::core::option::Option<super::super::super::common::v1::SeatObject>,
    #[prost(string, tag = "2")]
    pub new_identifier: ::prost::alloc::string::String,
    /// When omitted the service resolves the organization's current contract.
    #[prost(uint64, optional, tag = "3")]
    pub contract_id: ::core::option::Option<u64>,
}
