// This file is @generated by prost-build.
/// Date-only message (follows Google's google.type.Date pattern).
/// Avoids timezone ambiguity for billing period boundaries.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Date {
    #[prost(int32, tag = "1")]
    pub year: i32,
    #[prost(int32, tag = "2")]
    pub month: i32,
    #[prost(int32, tag = "3")]
    pub day: i32,
}
/// A single tier in a tiered pricing schedule.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingTier {
    /// Inclusive start of the tier (unit count).
    #[prost(int64, tag = "1")]
    pub start: i64,
    /// Exclusive end of the tier. -1 means unlimited.
    #[prost(int64, tag = "2")]
    pub end: i64,
    /// Rate per unit in cents-per-event (CPE).
    #[prost(int64, tag = "3")]
    pub rate_per_unit_cpe: i64,
}
/// Tiered pricing configuration for reserved and pay-as-you-go rates.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TieredPricingRate {
    #[prost(message, repeated, tag = "1")]
    pub tiers: ::prost::alloc::vec::Vec<PricingTier>,
}
/// A credit applied to a subscription or SKU.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Credit {
    #[prost(enumeration = "CreditKind", tag = "1")]
    pub kind: i32,
    /// Credit amount. Interpretation depends on kind:
    /// UNITS — number of units
    /// DOLLARS — amount in cents
    /// DISCOUNT — percentage (0-100)
    #[prost(int64, tag = "2")]
    pub amount: i64,
    /// If set, credit applies only to this SKU. Otherwise subscription-level.
    #[prost(enumeration = "StockKeepingUnit", optional, tag = "3")]
    pub sku: ::core::option::Option<i32>,
}
/// Per-category billing configuration.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CategoryConfig {
    /// Multiplier applied to raw event counts to get billable units.
    #[prost(int64, tag = "1")]
    pub unit_multiplier: i64,
    /// Reserved (committed) pricing rate.
    #[prost(message, optional, tag = "2")]
    pub reserved_rate: ::core::option::Option<TieredPricingRate>,
    /// Pay-as-you-go pricing rate.
    #[prost(message, optional, tag = "3")]
    pub payg_rate: ::core::option::Option<TieredPricingRate>,
    /// Reserved volume (committed units). Null means no reservation.
    #[prost(int64, optional, tag = "4")]
    pub reserved_volume: ::core::option::Option<i64>,
    /// Free units included before billing begins.
    #[prost(int64, tag = "5")]
    pub free_units: i64,
    /// Reserved pool budget in cents. Null if not using pooled reservations.
    #[prost(int64, optional, tag = "6")]
    pub reserved_pool_cents: ::core::option::Option<i64>,
    /// Per-category PAYG budget in cents. Null if using shared max_spend.
    #[prost(int64, optional, tag = "7")]
    pub payg_budget_cents: ::core::option::Option<i64>,
}
/// Per-SKU billing configuration.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkuConfig {
    #[prost(enumeration = "StockKeepingUnit", tag = "1")]
    pub sku: i32,
    /// Category configurations keyed by DataCategory uint32 value.
    #[prost(map = "uint32, message", tag = "2")]
    pub categories: ::std::collections::HashMap<u32, CategoryConfig>,
    /// Base price for this SKU in cents.
    #[prost(int64, tag = "3")]
    pub base_price_cents: i64,
    /// Per-SKU PAYG budget in cents.
    #[prost(int64, tag = "4")]
    pub payg_budget_cents: i64,
    /// Credits specific to this SKU.
    #[prost(message, repeated, tag = "5")]
    pub credits: ::prost::alloc::vec::Vec<Credit>,
}
/// Top-level billing configuration (payment method, channel, provider).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingConfig {
    #[prost(enumeration = "BillingType", tag = "1")]
    pub billing_type: i32,
    #[prost(enumeration = "BillingChannel", tag = "2")]
    pub channel: i32,
    #[prost(enumeration = "ExternalBillingProvider", optional, tag = "3")]
    pub external_billing_provider: ::core::option::Option<i32>,
}
/// Polymorphic value for subscription options (follows AnyValue pattern).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscriptionOptionValue {
    #[prost(oneof = "subscription_option_value::Value", tags = "1, 2, 3")]
    pub value: ::core::option::Option<subscription_option_value::Value>,
}
/// Nested message and enum types in `SubscriptionOptionValue`.
pub mod subscription_option_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntValue(i64),
        #[prost(double, tag = "2")]
        DoubleValue(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
    }
}
/// The main Contract message — encapsulates everything a customer has paid for.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    /// Format: {period_start}*{plan_id}*{price_hash}
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// Ruleset identifier. Null until rules engine exists.
    #[prost(string, optional, tag = "4")]
    pub ruleset_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "BillingInterval", tag = "6")]
    pub billing_interval: i32,
    #[prost(message, optional, tag = "7")]
    pub contract_period_start: ::core::option::Option<Date>,
    #[prost(message, optional, tag = "8")]
    pub contract_period_end: ::core::option::Option<Date>,
    #[prost(message, optional, tag = "9")]
    pub billing_config: ::core::option::Option<BillingConfig>,
    /// Platform fee in cents.
    #[prost(int64, tag = "10")]
    pub base_price_cents: i64,
    /// Shared PAYG budget in cents (0 if per-category budgets are used).
    #[prost(int64, tag = "11")]
    pub max_spend_cents: i64,
    /// Flat category configs keyed by DataCategory uint32 value (pre-engine).
    #[prost(map = "uint32, message", tag = "12")]
    pub category_configs: ::std::collections::HashMap<u32, CategoryConfig>,
    #[prost(message, repeated, tag = "13")]
    pub sku_configs: ::prost::alloc::vec::Vec<SkuConfig>,
    /// Subscription-level credits.
    #[prost(message, repeated, tag = "14")]
    pub credits: ::prost::alloc::vec::Vec<Credit>,
    /// Feature entitlements.
    #[prost(string, repeated, tag = "15")]
    pub features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Plan ID, tier, name, etc.
    #[prost(map = "string, string", tag = "16")]
    pub package_metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Subscription options (e.g. max members, custom retention).
    #[prost(map = "string, message", tag = "17")]
    pub subscription_options: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        SubscriptionOptionValue,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetContractRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetContractResponse {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Contract>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContractRequest {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Contract>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContractResponse {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<Contract>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StockKeepingUnit {
    Unspecified = 0,
    Errors = 1,
    Performance = 2,
    Spans = 3,
    Replays = 4,
    Cron = 5,
    Uptime = 6,
    Attachments = 7,
    Profiling = 8,
    ProfilingUi = 9,
    Logs = 10,
    Seer = 11,
    SizeAnalysis = 12,
    BuildDistribution = 13,
}
impl StockKeepingUnit {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STOCK_KEEPING_UNIT_UNSPECIFIED",
            Self::Errors => "STOCK_KEEPING_UNIT_ERRORS",
            Self::Performance => "STOCK_KEEPING_UNIT_PERFORMANCE",
            Self::Spans => "STOCK_KEEPING_UNIT_SPANS",
            Self::Replays => "STOCK_KEEPING_UNIT_REPLAYS",
            Self::Cron => "STOCK_KEEPING_UNIT_CRON",
            Self::Uptime => "STOCK_KEEPING_UNIT_UPTIME",
            Self::Attachments => "STOCK_KEEPING_UNIT_ATTACHMENTS",
            Self::Profiling => "STOCK_KEEPING_UNIT_PROFILING",
            Self::ProfilingUi => "STOCK_KEEPING_UNIT_PROFILING_UI",
            Self::Logs => "STOCK_KEEPING_UNIT_LOGS",
            Self::Seer => "STOCK_KEEPING_UNIT_SEER",
            Self::SizeAnalysis => "STOCK_KEEPING_UNIT_SIZE_ANALYSIS",
            Self::BuildDistribution => "STOCK_KEEPING_UNIT_BUILD_DISTRIBUTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STOCK_KEEPING_UNIT_UNSPECIFIED" => Some(Self::Unspecified),
            "STOCK_KEEPING_UNIT_ERRORS" => Some(Self::Errors),
            "STOCK_KEEPING_UNIT_PERFORMANCE" => Some(Self::Performance),
            "STOCK_KEEPING_UNIT_SPANS" => Some(Self::Spans),
            "STOCK_KEEPING_UNIT_REPLAYS" => Some(Self::Replays),
            "STOCK_KEEPING_UNIT_CRON" => Some(Self::Cron),
            "STOCK_KEEPING_UNIT_UPTIME" => Some(Self::Uptime),
            "STOCK_KEEPING_UNIT_ATTACHMENTS" => Some(Self::Attachments),
            "STOCK_KEEPING_UNIT_PROFILING" => Some(Self::Profiling),
            "STOCK_KEEPING_UNIT_PROFILING_UI" => Some(Self::ProfilingUi),
            "STOCK_KEEPING_UNIT_LOGS" => Some(Self::Logs),
            "STOCK_KEEPING_UNIT_SEER" => Some(Self::Seer),
            "STOCK_KEEPING_UNIT_SIZE_ANALYSIS" => Some(Self::SizeAnalysis),
            "STOCK_KEEPING_UNIT_BUILD_DISTRIBUTION" => Some(Self::BuildDistribution),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingInterval {
    Unspecified = 0,
    Monthly = 1,
    Annual = 2,
}
impl BillingInterval {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_INTERVAL_UNSPECIFIED",
            Self::Monthly => "BILLING_INTERVAL_MONTHLY",
            Self::Annual => "BILLING_INTERVAL_ANNUAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_INTERVAL_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_INTERVAL_MONTHLY" => Some(Self::Monthly),
            "BILLING_INTERVAL_ANNUAL" => Some(Self::Annual),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CreditKind {
    Unspecified = 0,
    Units = 1,
    Dollars = 2,
    Discount = 3,
}
impl CreditKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CREDIT_KIND_UNSPECIFIED",
            Self::Units => "CREDIT_KIND_UNITS",
            Self::Dollars => "CREDIT_KIND_DOLLARS",
            Self::Discount => "CREDIT_KIND_DISCOUNT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CREDIT_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "CREDIT_KIND_UNITS" => Some(Self::Units),
            "CREDIT_KIND_DOLLARS" => Some(Self::Dollars),
            "CREDIT_KIND_DISCOUNT" => Some(Self::Discount),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingType {
    Unspecified = 0,
    CreditCard = 1,
    Invoiced = 2,
    Partner = 3,
}
impl BillingType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_TYPE_UNSPECIFIED",
            Self::CreditCard => "BILLING_TYPE_CREDIT_CARD",
            Self::Invoiced => "BILLING_TYPE_INVOICED",
            Self::Partner => "BILLING_TYPE_PARTNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_TYPE_CREDIT_CARD" => Some(Self::CreditCard),
            "BILLING_TYPE_INVOICED" => Some(Self::Invoiced),
            "BILLING_TYPE_PARTNER" => Some(Self::Partner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingChannel {
    Unspecified = 0,
    SelfServe = 1,
    Sales = 2,
    Partner = 3,
}
impl BillingChannel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_CHANNEL_UNSPECIFIED",
            Self::SelfServe => "BILLING_CHANNEL_SELF_SERVE",
            Self::Sales => "BILLING_CHANNEL_SALES",
            Self::Partner => "BILLING_CHANNEL_PARTNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_CHANNEL_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_CHANNEL_SELF_SERVE" => Some(Self::SelfServe),
            "BILLING_CHANNEL_SALES" => Some(Self::Sales),
            "BILLING_CHANNEL_PARTNER" => Some(Self::Partner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExternalBillingProvider {
    Unspecified = 0,
    Stripe = 1,
    Vercel = 2,
}
impl ExternalBillingProvider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXTERNAL_BILLING_PROVIDER_UNSPECIFIED",
            Self::Stripe => "EXTERNAL_BILLING_PROVIDER_STRIPE",
            Self::Vercel => "EXTERNAL_BILLING_PROVIDER_VERCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXTERNAL_BILLING_PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "EXTERNAL_BILLING_PROVIDER_STRIPE" => Some(Self::Stripe),
            "EXTERNAL_BILLING_PROVIDER_VERCEL" => Some(Self::Vercel),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod contract_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ContractServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ContractServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ContractServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ContractServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ContractServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_contract(
            &mut self,
            request: impl tonic::IntoRequest<super::GetContractRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetContractResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.billing.v1.ContractService/GetContract",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.billing.v1.ContractService",
                        "GetContract",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_contract(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateContractRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateContractResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.billing.v1.ContractService/CreateContract",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "sentry_protos.billing.v1.ContractService",
                        "CreateContract",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod contract_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ContractServiceServer.
    #[async_trait]
    pub trait ContractService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_contract(
            &self,
            request: tonic::Request<super::GetContractRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetContractResponse>,
            tonic::Status,
        >;
        async fn create_contract(
            &self,
            request: tonic::Request<super::CreateContractRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateContractResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ContractServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ContractServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ContractServiceServer<T>
    where
        T: ContractService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.billing.v1.ContractService/GetContract" => {
                    #[allow(non_camel_case_types)]
                    struct GetContractSvc<T: ContractService>(pub Arc<T>);
                    impl<
                        T: ContractService,
                    > tonic::server::UnaryService<super::GetContractRequest>
                    for GetContractSvc<T> {
                        type Response = super::GetContractResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetContractRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ContractService>::get_contract(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetContractSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sentry_protos.billing.v1.ContractService/CreateContract" => {
                    #[allow(non_camel_case_types)]
                    struct CreateContractSvc<T: ContractService>(pub Arc<T>);
                    impl<
                        T: ContractService,
                    > tonic::server::UnaryService<super::CreateContractRequest>
                    for CreateContractSvc<T> {
                        type Response = super::CreateContractResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateContractRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ContractService>::create_contract(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateContractSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ContractServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.billing.v1.ContractService";
    impl<T> tonic::server::NamedService for ContractServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
