// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceUsageRequest {
    /// The organization's contract (contains PricingConfig with SKUConfigs, shared budgets, tiers)
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<
        super::super::contract::v1::GetContractResponse,
    >,
    /// Active credits/trials for the organization
    #[prost(message, optional, tag = "2")]
    pub credits: ::core::option::Option<super::super::trial::v1::GetTrialsResponse>,
    /// Usage data for the billing period
    #[prost(message, optional, tag = "3")]
    pub usage: ::core::option::Option<super::super::usage::v1::GetUsageResponse>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkuUsageSummary {
    #[prost(enumeration = "super::super::super::Sku", tag = "1")]
    pub sku: i32,
    /// Net cents consumed by this SKU in the billing period (after credits/trials applied).
    #[prost(uint64, tag = "2")]
    pub payg_spend_cents: u64,
    /// Total units consumed by this SKU in the billing period.
    #[prost(uint64, tag = "3")]
    pub usage_volume: u64,
}
/// Pricing breakdown for a shared budget spanning multiple SKUs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharedBudgetUsageSummary {
    #[prost(enumeration = "super::super::super::Sku", repeated, tag = "1")]
    pub skus: ::prost::alloc::vec::Vec<i32>,
    /// Net cents consumed across all SKUs in this shared budget (after credits/trials applied).
    #[prost(uint64, tag = "2")]
    pub payg_spend_cents: u64,
    /// Per-SKU breakdown within the shared budget.
    #[prost(message, repeated, tag = "3")]
    pub sku_summaries: ::prost::alloc::vec::Vec<SkuUsageSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceUsageResponse {
    /// Per-SKU pricing breakdown (for SKUs with individual budgets).
    #[prost(message, repeated, tag = "1")]
    pub sku_summaries: ::prost::alloc::vec::Vec<SkuUsageSummary>,
    /// Per-shared-budget pricing breakdown (for SKUs sharing a budget).
    #[prost(message, repeated, tag = "2")]
    pub shared_budget_summaries: ::prost::alloc::vec::Vec<SharedBudgetUsageSummary>,
    /// Grand total net spend in cents across all SKUs (after credits/trials applied).
    #[prost(uint64, tag = "3")]
    pub total_payg_spend_cents: u64,
    /// Grand total usage volume across all SKUs.
    #[prost(uint64, tag = "4")]
    pub total_usage_volume: u64,
}
