// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Date {
    #[prost(uint32, tag = "1")]
    pub year: u32,
    #[prost(uint32, tag = "2")]
    pub month: u32,
    #[prost(uint32, tag = "3")]
    pub day: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub country_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub postal_code: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub address_line_1: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub address_line_2: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub address_line_3: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BillingConfig {
    #[prost(enumeration = "BillingType", tag = "1")]
    pub billing_type: i32,
    #[prost(enumeration = "BillingChannel", tag = "2")]
    pub channel: i32,
    #[prost(enumeration = "ExternalBillingProvider", tag = "3")]
    pub external_billing_provider: i32,
    #[prost(message, optional, tag = "4")]
    pub address: ::core::option::Option<Address>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Credit {
    #[prost(enumeration = "CreditType", tag = "1")]
    pub r#type: i32,
    /// Volume in units (UNITS) or amount in cents (DOLLARS).
    #[prost(uint64, tag = "2")]
    pub amount: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingTier {
    /// Start of the tier range (inclusive).
    #[prost(int64, tag = "1")]
    pub start: i64,
    /// End of the tier range (inclusive). -1 means unlimited.
    #[prost(int64, tag = "2")]
    pub end: i64,
    /// Rate per unit in CPE units.
    #[prost(uint64, tag = "3")]
    pub rate_per_unit_cpe: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TieredPricingRate {
    #[prost(message, repeated, tag = "1")]
    pub tiers: ::prost::alloc::vec::Vec<PricingTier>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkuConfig {
    #[prost(enumeration = "Sku", tag = "1")]
    pub sku: i32,
    /// Base price for the SKU (upgraded reserved volumes or add-on activation fees)
    #[prost(uint64, tag = "2")]
    pub base_price_cents: u64,
    /// Per-SKU PAYG spend cap. Absent if part of a shared budget
    #[prost(uint64, optional, tag = "3")]
    pub payg_budget_cents: ::core::option::Option<u64>,
    #[prost(uint64, tag = "4")]
    pub reserved_volume: u64,
    #[prost(message, optional, tag = "5")]
    pub payg_rate: ::core::option::Option<TieredPricingRate>,
    /// for reserved budget SKUs
    #[prost(message, optional, tag = "6")]
    pub reserved_rate: ::core::option::Option<TieredPricingRate>,
    #[prost(message, repeated, tag = "7")]
    pub credits: ::prost::alloc::vec::Vec<Credit>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharedSkuBudget {
    #[prost(message, repeated, tag = "1")]
    pub skus: ::prost::alloc::vec::Vec<SkuConfig>,
    #[prost(uint64, tag = "2")]
    pub reserved_budget_cents: u64,
    #[prost(uint64, tag = "3")]
    pub payg_budget_cents: u64,
    #[prost(message, repeated, tag = "4")]
    pub credits: ::prost::alloc::vec::Vec<Credit>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OptionValue {
    #[prost(oneof = "option_value::Value", tags = "1, 2, 3")]
    pub value: ::core::option::Option<option_value::Value>,
}
/// Nested message and enum types in `OptionValue`.
pub mod option_value {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(int64, tag = "2")]
        IntValue(i64),
        #[prost(bool, tag = "3")]
        BoolValue(bool),
    }
}
/// Represents what a customer has paid for. Used for cost calculation,
/// enforcing quotas, creating invoices, and maybe others.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    /// The set of BillingRules that the BillingRulesEngine has to execute for this contract.
    #[prost(string, tag = "3")]
    pub ruleset_version: ::prost::alloc::string::String,
    /// includes information like plan ID, tier, etc.
    #[prost(map = "string, string", tag = "4")]
    pub package_metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Contract interval — determines when to charge package base price / subscription fee.
    #[prost(message, optional, tag = "5")]
    pub contract_start_date: ::core::option::Option<Date>,
    #[prost(message, optional, tag = "6")]
    pub contract_end_date: ::core::option::Option<Date>,
    /// Determines when to reset quotas and create an invoice.
    #[prost(message, optional, tag = "7")]
    pub billing_period_start_date: ::core::option::Option<Date>,
    #[prost(message, optional, tag = "8")]
    pub billing_period_end_date: ::core::option::Option<Date>,
    /// Entitlements, used in frontend features.
    #[prost(map = "string, bool", tag = "9")]
    pub features: ::std::collections::HashMap<::prost::alloc::string::String, bool>,
    /// Used for quotas and cost calculations.
    #[prost(message, repeated, tag = "10")]
    pub sku_configs: ::prost::alloc::vec::Vec<SkuConfig>,
    #[prost(message, repeated, tag = "11")]
    pub shared_sku_budgets: ::prost::alloc::vec::Vec<SharedSkuBudget>,
    /// PAYG budget (max spend).
    #[prost(uint64, tag = "12")]
    pub max_spend_cents: u64,
    /// Package base price / subscription fee.
    #[prost(uint64, tag = "13")]
    pub base_price_cents: u64,
    /// Used for invoicing.
    #[prost(message, optional, tag = "14")]
    pub billing_config: ::core::option::Option<BillingConfig>,
    /// Org-level credits.
    #[prost(message, repeated, tag = "15")]
    pub credits: ::prost::alloc::vec::Vec<Credit>,
    /// Catch-all for overrides and information not covered above.
    #[prost(map = "string, message", tag = "16")]
    pub custom_options: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        OptionValue,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingType {
    Unspecified = 0,
    Invoiced = 1,
    CreditCard = 2,
    Partner = 3,
}
impl BillingType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_TYPE_UNSPECIFIED",
            Self::Invoiced => "BILLING_TYPE_INVOICED",
            Self::CreditCard => "BILLING_TYPE_CREDIT_CARD",
            Self::Partner => "BILLING_TYPE_PARTNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_TYPE_INVOICED" => Some(Self::Invoiced),
            "BILLING_TYPE_CREDIT_CARD" => Some(Self::CreditCard),
            "BILLING_TYPE_PARTNER" => Some(Self::Partner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BillingChannel {
    Unspecified = 0,
    SelfServe = 1,
    Sales = 2,
    Partner = 3,
}
impl BillingChannel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BILLING_CHANNEL_UNSPECIFIED",
            Self::SelfServe => "BILLING_CHANNEL_SELF_SERVE",
            Self::Sales => "BILLING_CHANNEL_SALES",
            Self::Partner => "BILLING_CHANNEL_PARTNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BILLING_CHANNEL_UNSPECIFIED" => Some(Self::Unspecified),
            "BILLING_CHANNEL_SELF_SERVE" => Some(Self::SelfServe),
            "BILLING_CHANNEL_SALES" => Some(Self::Sales),
            "BILLING_CHANNEL_PARTNER" => Some(Self::Partner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExternalBillingProvider {
    Unspecified = 0,
    Stripe = 1,
    Vercel = 2,
}
impl ExternalBillingProvider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXTERNAL_BILLING_PROVIDER_UNSPECIFIED",
            Self::Stripe => "EXTERNAL_BILLING_PROVIDER_STRIPE",
            Self::Vercel => "EXTERNAL_BILLING_PROVIDER_VERCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXTERNAL_BILLING_PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "EXTERNAL_BILLING_PROVIDER_STRIPE" => Some(Self::Stripe),
            "EXTERNAL_BILLING_PROVIDER_VERCEL" => Some(Self::Vercel),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Sku {
    Unspecified = 0,
    Errors = 1,
    Spans = 2,
    Replays = 3,
    Transactions = 4,
    Cron = 5,
    Uptime = 6,
    Attachments = 7,
    Profiling = 8,
    ProfilingUi = 9,
    Logs = 10,
    Seer = 11,
    SizeAnalysis = 12,
    BuildDistribution = 13,
}
impl Sku {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SKU_UNSPECIFIED",
            Self::Errors => "SKU_ERRORS",
            Self::Spans => "SKU_SPANS",
            Self::Replays => "SKU_REPLAYS",
            Self::Transactions => "SKU_TRANSACTIONS",
            Self::Cron => "SKU_CRON",
            Self::Uptime => "SKU_UPTIME",
            Self::Attachments => "SKU_ATTACHMENTS",
            Self::Profiling => "SKU_PROFILING",
            Self::ProfilingUi => "SKU_PROFILING_UI",
            Self::Logs => "SKU_LOGS",
            Self::Seer => "SKU_SEER",
            Self::SizeAnalysis => "SKU_SIZE_ANALYSIS",
            Self::BuildDistribution => "SKU_BUILD_DISTRIBUTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SKU_UNSPECIFIED" => Some(Self::Unspecified),
            "SKU_ERRORS" => Some(Self::Errors),
            "SKU_SPANS" => Some(Self::Spans),
            "SKU_REPLAYS" => Some(Self::Replays),
            "SKU_TRANSACTIONS" => Some(Self::Transactions),
            "SKU_CRON" => Some(Self::Cron),
            "SKU_UPTIME" => Some(Self::Uptime),
            "SKU_ATTACHMENTS" => Some(Self::Attachments),
            "SKU_PROFILING" => Some(Self::Profiling),
            "SKU_PROFILING_UI" => Some(Self::ProfilingUi),
            "SKU_LOGS" => Some(Self::Logs),
            "SKU_SEER" => Some(Self::Seer),
            "SKU_SIZE_ANALYSIS" => Some(Self::SizeAnalysis),
            "SKU_BUILD_DISTRIBUTION" => Some(Self::BuildDistribution),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CreditType {
    Unspecified = 0,
    Units = 1,
    Dollars = 2,
}
impl CreditType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CREDIT_TYPE_UNSPECIFIED",
            Self::Units => "CREDIT_TYPE_UNITS",
            Self::Dollars => "CREDIT_TYPE_DOLLARS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CREDIT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CREDIT_TYPE_UNITS" => Some(Self::Units),
            "CREDIT_TYPE_DOLLARS" => Some(Self::Dollars),
            _ => None,
        }
    }
}
/// Classifies the type of data being tracked.
/// Only types that we track usage of should be included here, not to be confused
/// with DataCategory in relay, or in sentry, which may include other types that
/// we don’t track for usage.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataCategory {
    /// Reserved and unused.
    Unspecified = 0,
    /// Error events and Events with an event_type not explicitly listed below.
    Error = 1,
    /// Transaction events.
    Transaction = 2,
    /// An attachment. Quantity is the size of the attachment in bytes.
    Attachment = 3,
    /// Processed profiles (all profiles, whether or not we store them).
    Profile = 4,
    /// Session Replays.
    Replay = 5,
    /// Monitor check-ins.
    Monitor = 6,
    /// Spans from which we extracted metrics.
    Span = 7,
    /// User Feedback (UserReportV2).
    UserReportV2 = 8,
    /// Milliseconds per indexed profile chunk, excluding UI profile chunks.
    ProfileDuration = 9,
    /// Log event total bytes.
    LogByte = 10,
    /// Profile duration of a UI profile (milliseconds per indexed UI profile chunk).
    ProfileDurationUi = 11,
    /// Seer Autofix run events.
    SeerAutofix = 12,
    /// Seer Scanner run events.
    SeerScanner = 13,
    /// Size analysis of preprod build artifacts.
    SizeAnalysis = 14,
    /// Installable build artifact uploads.
    InstallableBuild = 15,
    /// Trace metric items.
    TraceMetric = 16,
    /// Any other data category not known by this version.
    Unknown = -1,
}
impl DataCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_CATEGORY_UNSPECIFIED",
            Self::Error => "DATA_CATEGORY_ERROR",
            Self::Transaction => "DATA_CATEGORY_TRANSACTION",
            Self::Attachment => "DATA_CATEGORY_ATTACHMENT",
            Self::Profile => "DATA_CATEGORY_PROFILE",
            Self::Replay => "DATA_CATEGORY_REPLAY",
            Self::Monitor => "DATA_CATEGORY_MONITOR",
            Self::Span => "DATA_CATEGORY_SPAN",
            Self::UserReportV2 => "DATA_CATEGORY_USER_REPORT_V2",
            Self::ProfileDuration => "DATA_CATEGORY_PROFILE_DURATION",
            Self::LogByte => "DATA_CATEGORY_LOG_BYTE",
            Self::ProfileDurationUi => "DATA_CATEGORY_PROFILE_DURATION_UI",
            Self::SeerAutofix => "DATA_CATEGORY_SEER_AUTOFIX",
            Self::SeerScanner => "DATA_CATEGORY_SEER_SCANNER",
            Self::SizeAnalysis => "DATA_CATEGORY_SIZE_ANALYSIS",
            Self::InstallableBuild => "DATA_CATEGORY_INSTALLABLE_BUILD",
            Self::TraceMetric => "DATA_CATEGORY_TRACE_METRIC",
            Self::Unknown => "DATA_CATEGORY_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_CATEGORY_ERROR" => Some(Self::Error),
            "DATA_CATEGORY_TRANSACTION" => Some(Self::Transaction),
            "DATA_CATEGORY_ATTACHMENT" => Some(Self::Attachment),
            "DATA_CATEGORY_PROFILE" => Some(Self::Profile),
            "DATA_CATEGORY_REPLAY" => Some(Self::Replay),
            "DATA_CATEGORY_MONITOR" => Some(Self::Monitor),
            "DATA_CATEGORY_SPAN" => Some(Self::Span),
            "DATA_CATEGORY_USER_REPORT_V2" => Some(Self::UserReportV2),
            "DATA_CATEGORY_PROFILE_DURATION" => Some(Self::ProfileDuration),
            "DATA_CATEGORY_LOG_BYTE" => Some(Self::LogByte),
            "DATA_CATEGORY_PROFILE_DURATION_UI" => Some(Self::ProfileDurationUi),
            "DATA_CATEGORY_SEER_AUTOFIX" => Some(Self::SeerAutofix),
            "DATA_CATEGORY_SEER_SCANNER" => Some(Self::SeerScanner),
            "DATA_CATEGORY_SIZE_ANALYSIS" => Some(Self::SizeAnalysis),
            "DATA_CATEGORY_INSTALLABLE_BUILD" => Some(Self::InstallableBuild),
            "DATA_CATEGORY_TRACE_METRIC" => Some(Self::TraceMetric),
            "DATA_CATEGORY_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
