// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnforcementDecision {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    #[prost(uint64, tag = "2")]
    pub organization_id: u64,
    #[prost(enumeration = "EnforcementType", tag = "3")]
    pub enforcement_type: i32,
    #[prost(string, tag = "4")]
    pub explanation: ::prost::alloc::string::String,
    /// Even though we bill for SKUs, relay ingests data categories, so enforcement
    /// decisions are on a per-datacategory basis
    #[prost(enumeration = "super::super::super::DataCategory", tag = "5")]
    pub data_category: i32,
    #[prost(message, optional, tag = "6")]
    pub decision_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub expiration_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EnforcementType {
    Unspecified = 0,
    RateLimit = 1,
    Sample = 2,
}
impl EnforcementType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENFORCEMENT_TYPE_UNSPECIFIED",
            Self::RateLimit => "ENFORCEMENT_TYPE_RATE_LIMIT",
            Self::Sample => "ENFORCEMENT_TYPE_SAMPLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENFORCEMENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ENFORCEMENT_TYPE_RATE_LIMIT" => Some(Self::RateLimit),
            "ENFORCEMENT_TYPE_SAMPLE" => Some(Self::Sample),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricedSkuUsage {
    #[prost(enumeration = "super::super::contract::v1::Sku", tag = "1")]
    pub sku: i32,
    #[prost(uint64, tag = "2")]
    pub current_used_cents: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PricedUsage {
    /// the contract contains all the information about the
    /// organization's budget(s)
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    /// The amount of money used up for a specific SKU in the current
    /// billing period. Credits have already been applied to this calculation
    #[prost(message, repeated, tag = "2")]
    pub priced_sku_usage: ::prost::alloc::vec::Vec<PricedSkuUsage>,
}
