// This file is @generated by prost-build.
/// Builds the pending change that rolls the contract onto the latest catalog's
/// free package.
///
/// An older package generation must not keep an organization on a retired free
/// tier. Free is monthly and cannot retain sponsorship or paid-plan user
/// overrides; unset PendingChange fields mean "no change" to rollover, so
/// interval and sponsorship are only populated when they must actually change.
/// Shared by deferred cancel (which stages the change) and immediate downgrade
/// (which applies it now).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildLatestFreeChangeRequest {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<super::super::contract::v2::Contract>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildLatestFreeChangeResponse {
    #[prost(message, optional, tag = "1")]
    pub change: ::core::option::Option<super::super::super::common::v1::PendingChange>,
}
/// Drops add-ons on the contract now. Callers pass the contract those add-ons
/// currently sit on: the still-current paid contract for deferred cancel, or
/// the newly opened free contract after an immediate rollover.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveActivationsRequest {
    #[prost(message, optional, tag = "1")]
    pub contract: ::core::option::Option<super::super::contract::v2::Contract>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveActivationsResponse {}
