// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineItemConfig {
    /// Base price for the line item (upgraded reserved volumes or add-on activation fees)
    #[deprecated]
    #[prost(uint64, tag = "1")]
    pub base_price_cents: u64,
    #[prost(message, optional, tag = "3")]
    pub payg_rate: ::core::option::Option<
        super::super::super::common::v1::TieredPricingRate,
    >,
    /// for reserved budget line items
    #[prost(message, optional, tag = "4")]
    pub reserved_rate: ::core::option::Option<
        super::super::super::common::v1::TieredPricingRate,
    >,
    #[prost(message, optional, tag = "7")]
    pub line_item: ::core::option::Option<
        super::super::super::common::v1::LineItemDetails,
    >,
    /// Whether this LineItem is included in the base package or not (ie Seer)
    #[prost(bool, tag = "8")]
    pub is_optional_add_on: bool,
    /// Used for calculating spend that should not apply towards an organization's PAYG budget (ie Seer seats)
    #[prost(message, optional, tag = "9")]
    pub uncapped_rate: ::core::option::Option<
        super::super::super::common::v1::TieredPricingRate,
    >,
    /// how many of this lineitem are included in the package, the customer can reserve more on their contract
    #[prost(oneof = "line_item_config::IncludedReservedUnits", tags = "5, 6")]
    pub included_reserved_units: ::core::option::Option<
        line_item_config::IncludedReservedUnits,
    >,
    /// How many units are available for a PackageConfig during a subscription trial? For packages that are not eligible for trials,
    /// this field will be unset for all line items.
    #[prost(oneof = "line_item_config::TrialUnits", tags = "10, 11")]
    pub trial_units: ::core::option::Option<line_item_config::TrialUnits>,
}
/// Nested message and enum types in `LineItemConfig`.
pub mod line_item_config {
    /// how many of this lineitem are included in the package, the customer can reserve more on their contract
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum IncludedReservedUnits {
        #[prost(bool, tag = "5")]
        IsUnlimited(bool),
        /// the type communicates whether the line item is unlimited or not, additionally reserved budget line items have a non-zero reserved_rate in addition to 0 reserved_units
        #[prost(uint64, tag = "6")]
        NumReservedUnits(u64),
    }
    /// How many units are available for a PackageConfig during a subscription trial? For packages that are not eligible for trials,
    /// this field will be unset for all line items.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TrialUnits {
        #[prost(bool, tag = "10")]
        IsUnlimitedTrial(bool),
        #[prost(uint64, tag = "11")]
        NumTrialUnits(u64),
    }
}
/// Represents a budget included in a package that is collectively used by one or more line items,
/// allowing multiple line items to draw from the same reserved budget.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharedLineItemPool {
    /// how much money this shared pool has. For example, if logs costs $1.00 per GB and metrics
    /// costs $1.00 per GB and we wanted to give metrics and logs a shared 5GB pool, the reserved_pool_cents
    /// would be 500 ($5)
    ///
    /// DEPRECATED: Use reserved_tier
    #[deprecated]
    #[prost(uint64, tag = "1")]
    pub reserved_pool_cents: u64,
    #[prost(message, repeated, tag = "3")]
    pub line_items: ::prost::alloc::vec::Vec<
        super::super::super::common::v1::LineItemDetails,
    >,
    /// Whether this LineItem is included in the base package or not (ie Seer)
    #[prost(bool, tag = "4")]
    pub is_optional_add_on: bool,
    /// The unique line item details used when invoicing this shared pool.
    #[prost(message, optional, tag = "5")]
    pub shared_line_item: ::core::option::Option<
        super::super::super::common::v1::LineItemDetails,
    >,
    /// Cost of the shared line item pool, in cents(a customer can pay $X and get $Y of credit, where X!=Y).
    ///
    /// DEPRECATED: Use reserved_tier
    #[deprecated]
    #[prost(uint64, tag = "6")]
    pub base_price_cents: u64,
    /// DEPRECATED: Use reserved_tier
    #[deprecated]
    #[prost(message, optional, tag = "7")]
    pub flexible_base_price_cents: ::core::option::Option<
        super::super::super::common::v1::FlexiblePrice,
    >,
    /// Similar to LineItemConfig.reserved_rate, this field will hold the list of available reserved tiers for this line item
    /// as well as the prices for each respective tier.
    #[prost(message, optional, tag = "8")]
    pub reserved_tier: ::core::option::Option<
        super::super::super::common::v1::TieredPricingRate,
    >,
    /// How many units are available for a PackageConfig during a subscription trial? For packages that are not eligible for trials,
    /// this field will be unset for all line items.
    #[prost(oneof = "shared_line_item_pool::TrialUnits", tags = "9, 10")]
    pub trial_units: ::core::option::Option<shared_line_item_pool::TrialUnits>,
}
/// Nested message and enum types in `SharedLineItemPool`.
pub mod shared_line_item_pool {
    /// How many units are available for a PackageConfig during a subscription trial? For packages that are not eligible for trials,
    /// this field will be unset for all line items.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum TrialUnits {
        #[prost(bool, tag = "9")]
        IsUnlimitedTrial(bool),
        #[prost(uint64, tag = "10")]
        NumTrialUnits(u64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageConfig {
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub line_item_configs: ::prost::alloc::vec::Vec<LineItemConfig>,
    #[prost(message, repeated, tag = "3")]
    pub shared_line_item_pools: ::prost::alloc::vec::Vec<SharedLineItemPool>,
    /// Base price for the package.
    #[deprecated]
    #[prost(uint64, tag = "4")]
    pub base_price_cents: u64,
    #[prost(message, optional, tag = "8")]
    pub flexible_base_price_cents: ::core::option::Option<
        super::super::super::common::v1::FlexiblePrice,
    >,
    /// Deprecated. Use supported_month_intervals.
    #[deprecated]
    #[prost(enumeration = "super::super::super::common::v1::BillingInterval", tag = "5")]
    pub billing_interval: i32,
    #[prost(string, tag = "6")]
    pub title: ::prost::alloc::string::String,
    /// Number-of-months billing intervals this package offers.
    /// \[1\] = monthly only, \[1, 12\] = monthly or annual, \[12\] = annual only.
    #[prost(uint32, repeated, tag = "7")]
    pub supported_month_intervals: ::prost::alloc::vec::Vec<u32>,
    /// Title shown in admin interfaces, not customer-facing.
    #[prost(string, tag = "9")]
    pub admin_title: ::prost::alloc::string::String,
    /// Whether the package is treated as enterprise in the UI (display name,
    /// upsell suppression).
    #[prost(bool, tag = "10")]
    pub is_enterprise: bool,
    /// Whether the package can be chosen in the self-serve checkout flow.
    #[prost(bool, tag = "11")]
    pub user_selectable: bool,
    /// Whether the package has pay-as-you-go (PAYG) modes.
    #[prost(bool, tag = "12")]
    pub has_payg_modes: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPackageRequest {
    #[prost(string, tag = "1")]
    pub package_uid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPackageResponse {
    #[prost(message, optional, tag = "1")]
    pub package_config: ::core::option::Option<PackageConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPackageForTierRequest {
    #[prost(string, tag = "1")]
    pub package_uid: ::prost::alloc::string::String,
    #[prost(enumeration = "PackageTier", tag = "2")]
    pub tier: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPackageForTierResponse {
    #[prost(message, optional, tag = "1")]
    pub package_config: ::core::option::Option<PackageConfig>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PackageTier {
    Unspecified = 0,
    Free = 1,
    Team = 2,
    Business = 3,
}
impl PackageTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PACKAGE_TIER_UNSPECIFIED",
            Self::Free => "PACKAGE_TIER_FREE",
            Self::Team => "PACKAGE_TIER_TEAM",
            Self::Business => "PACKAGE_TIER_BUSINESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PACKAGE_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "PACKAGE_TIER_FREE" => Some(Self::Free),
            "PACKAGE_TIER_TEAM" => Some(Self::Team),
            "PACKAGE_TIER_BUSINESS" => Some(Self::Business),
            _ => None,
        }
    }
}
