// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpendAllocationUsage {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(string, tag = "2")]
    pub line_item_uid: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub allocated: u64,
    #[prost(uint64, tag = "4")]
    pub used: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSpendAllocationStateRequest {
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpendAllocationStateResponse {
    #[prost(message, repeated, tag = "1")]
    pub usages: ::prost::alloc::vec::Vec<SpendAllocationUsage>,
    #[prost(message, optional, tag = "2")]
    pub simulated_usage: ::core::option::Option<
        super::super::usage::v1::GetUsageResponse,
    >,
}
