// This file is @generated by prost-build.
/// Estimates what a contract will use for the remainder of its on-demand
/// period, so a customer sees a full period rather than a series that stops
/// at today.
///
/// The estimate is a weighted average of the contract's recent daily usage,
/// decayed so that older days count for less. The sample reaches back into
/// prior billing periods, because a contract's own period is a poor sample on
/// its first days.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectedDailyBreakdownRequest {
    /// The contract whose remaining on-demand period should be projected.
    #[prost(uint64, tag = "1")]
    pub contract_id: u64,
    /// The day the projection is made from. Days up to and including this one
    /// are sampled; days strictly after it are projected, through the
    /// contract's on-demand period end.
    #[prost(message, optional, tag = "2")]
    pub current_date: ::core::option::Option<super::super::super::Date>,
}
/// One line item's projected per-outcome quantities on a projected date.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectedLineItemOutcomes {
    /// Package line item uid, matching the line items UsagePricer reports
    /// actual usage against, so a caller can align the two by uid.
    #[prost(string, tag = "1")]
    pub line_item_uid: ::prost::alloc::string::String,
    /// The estimate for each of the seven outcome fields, rounded to whole
    /// counts. Two fields are not projected as recorded: quantities rejected
    /// for want of quota are counted as accepted, because that is what the
    /// customer would have sent, and over_quota itself is projected as zero,
    /// so a period that ran over quota does not forecast itself over again.
    #[prost(message, optional, tag = "2")]
    pub outcomes: ::core::option::Option<super::super::super::UsageData>,
}
/// One projected calendar date.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectedDailyOutcomes {
    #[prost(message, optional, tag = "1")]
    pub date: ::core::option::Option<super::super::super::Date>,
    /// Every line item the sample saw, including ones estimated at zero.
    #[prost(message, repeated, tag = "2")]
    pub line_items: ::prost::alloc::vec::Vec<ProjectedLineItemOutcomes>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectedDailyBreakdownResponse {
    /// Projected days in ascending date order, one per day between
    /// `current_date` (exclusive) and the contract's on-demand period end
    /// (inclusive). Empty when the period has already ended.
    ///
    /// Every projected day repeats the same estimate, because the estimate is a
    /// single weighted average per line item rather than a per-day forecast.
    #[prost(message, repeated, tag = "1")]
    pub days: ::prost::alloc::vec::Vec<ProjectedDailyOutcomes>,
}
