// This file is @generated by prost-build.
/// Classifies the type of data being tracked.
/// Only types that we track usage of should be included here, not to be confused
/// with DataCategory in relay, or in sentry, which may include other types that
/// we don’t track for usage.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataCategory {
    /// Reserved and unused.
    Unspecified = 0,
    /// Error events and Events with an event_type not explicitly listed below.
    Error = 1,
    /// Transaction events.
    Transaction = 2,
    /// An attachment. Quantity is the size of the attachment in bytes.
    Attachment = 3,
    /// Processed profiles (all profiles, whether or not we store them).
    Profile = 4,
    /// Session Replays.
    Replay = 5,
    /// Monitor check-ins.
    Monitor = 6,
    /// Spans from which we extracted metrics.
    Span = 7,
    /// User Feedback (UserReportV2).
    UserReportV2 = 8,
    /// Milliseconds per indexed profile chunk, excluding UI profile chunks.
    ProfileDuration = 9,
    /// Log event total bytes.
    LogByte = 10,
    /// Profile duration of a UI profile (milliseconds per indexed UI profile chunk).
    ProfileDurationUi = 11,
    /// Seer Autofix run events.
    SeerAutofix = 12,
    /// Seer Scanner run events.
    SeerScanner = 13,
    /// Size analysis of preprod build artifacts.
    SizeAnalysis = 14,
    /// Installable build artifact uploads.
    InstallableBuild = 15,
    /// Trace metric items.
    TraceMetric = 16,
    /// Any other data category not known by this version.
    Unknown = -1,
}
impl DataCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_CATEGORY_UNSPECIFIED",
            Self::Error => "DATA_CATEGORY_ERROR",
            Self::Transaction => "DATA_CATEGORY_TRANSACTION",
            Self::Attachment => "DATA_CATEGORY_ATTACHMENT",
            Self::Profile => "DATA_CATEGORY_PROFILE",
            Self::Replay => "DATA_CATEGORY_REPLAY",
            Self::Monitor => "DATA_CATEGORY_MONITOR",
            Self::Span => "DATA_CATEGORY_SPAN",
            Self::UserReportV2 => "DATA_CATEGORY_USER_REPORT_V2",
            Self::ProfileDuration => "DATA_CATEGORY_PROFILE_DURATION",
            Self::LogByte => "DATA_CATEGORY_LOG_BYTE",
            Self::ProfileDurationUi => "DATA_CATEGORY_PROFILE_DURATION_UI",
            Self::SeerAutofix => "DATA_CATEGORY_SEER_AUTOFIX",
            Self::SeerScanner => "DATA_CATEGORY_SEER_SCANNER",
            Self::SizeAnalysis => "DATA_CATEGORY_SIZE_ANALYSIS",
            Self::InstallableBuild => "DATA_CATEGORY_INSTALLABLE_BUILD",
            Self::TraceMetric => "DATA_CATEGORY_TRACE_METRIC",
            Self::Unknown => "DATA_CATEGORY_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_CATEGORY_ERROR" => Some(Self::Error),
            "DATA_CATEGORY_TRANSACTION" => Some(Self::Transaction),
            "DATA_CATEGORY_ATTACHMENT" => Some(Self::Attachment),
            "DATA_CATEGORY_PROFILE" => Some(Self::Profile),
            "DATA_CATEGORY_REPLAY" => Some(Self::Replay),
            "DATA_CATEGORY_MONITOR" => Some(Self::Monitor),
            "DATA_CATEGORY_SPAN" => Some(Self::Span),
            "DATA_CATEGORY_USER_REPORT_V2" => Some(Self::UserReportV2),
            "DATA_CATEGORY_PROFILE_DURATION" => Some(Self::ProfileDuration),
            "DATA_CATEGORY_LOG_BYTE" => Some(Self::LogByte),
            "DATA_CATEGORY_PROFILE_DURATION_UI" => Some(Self::ProfileDurationUi),
            "DATA_CATEGORY_SEER_AUTOFIX" => Some(Self::SeerAutofix),
            "DATA_CATEGORY_SEER_SCANNER" => Some(Self::SeerScanner),
            "DATA_CATEGORY_SIZE_ANALYSIS" => Some(Self::SizeAnalysis),
            "DATA_CATEGORY_INSTALLABLE_BUILD" => Some(Self::InstallableBuild),
            "DATA_CATEGORY_TRACE_METRIC" => Some(Self::TraceMetric),
            "DATA_CATEGORY_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
/// Aggregated usage counts for a single data category.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsageData {
    #[prost(uint64, tag = "1")]
    pub total: u64,
    #[prost(uint64, tag = "2")]
    pub accepted: u64,
    #[prost(uint64, tag = "3")]
    pub dropped: u64,
    #[prost(uint64, tag = "4")]
    pub filtered: u64,
    #[prost(uint64, tag = "5")]
    pub over_quota: u64,
    #[prost(uint64, tag = "6")]
    pub smart_limit: u64,
    #[prost(uint64, tag = "7")]
    pub dynamic_sampling: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageRequest {
    #[prost(uint64, tag = "1")]
    pub organization_id: u64,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CategoryUsage {
    #[prost(enumeration = "DataCategory", tag = "1")]
    pub category: i32,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<UsageData>,
}
/// Usage data for a single day.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DailyUsage {
    #[prost(message, optional, tag = "1")]
    pub date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "2")]
    pub usage: ::prost::alloc::vec::Vec<CategoryUsage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageResponse {
    /// Usage broken down by day, each containing per-category usage.
    #[prost(message, repeated, tag = "1")]
    pub days: ::prost::alloc::vec::Vec<DailyUsage>,
}
/// Generated client implementations.
pub mod usage_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct UsageServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UsageServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UsageServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UsageServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UsageServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_usage(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUsageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUsageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sentry_protos.billing.v1.UsageService/GetUsage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("sentry_protos.billing.v1.UsageService", "GetUsage"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod usage_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with UsageServiceServer.
    #[async_trait]
    pub trait UsageService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_usage(
            &self,
            request: tonic::Request<super::GetUsageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUsageResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct UsageServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> UsageServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for UsageServiceServer<T>
    where
        T: UsageService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sentry_protos.billing.v1.UsageService/GetUsage" => {
                    #[allow(non_camel_case_types)]
                    struct GetUsageSvc<T: UsageService>(pub Arc<T>);
                    impl<
                        T: UsageService,
                    > tonic::server::UnaryService<super::GetUsageRequest>
                    for GetUsageSvc<T> {
                        type Response = super::GetUsageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUsageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UsageService>::get_usage(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUsageSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for UsageServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sentry_protos.billing.v1.UsageService";
    impl<T> tonic::server::NamedService for UsageServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
