syntax = "proto3";

package sentry_protos.billing.v1.services.seat_activity.v1;

import "google/protobuf/timestamp.proto";
import "sentry_protos/billing/v1/common/v1/seat_status.proto";
import "sentry_protos/billing/v1/seat_category.proto";

message SeatObject {
  uint64 organization_id = 1;
  uint64 project_id = 2;
  sentry_protos.billing.v1.SeatCategory seat_category = 3;
  string external_product_display_name = 4;
  string external_product_identifier = 5;
}

message SeatState {
  string external_product_identifier = 1;
  sentry_protos.billing.v1.common.v1.SeatStatus current_status = 2;
  optional google.protobuf.Timestamp created_ts = 3;
  optional google.protobuf.Timestamp last_action_ts = 4;
  google.protobuf.Timestamp read_ts = 5;
}

message SeatActionRecord {
  uint64 contract_id = 1;
  uint64 organization_id = 2;
  uint64 project_id = 3;
  google.protobuf.Timestamp timestamp = 4;
  sentry_protos.billing.v1.common.v1.SeatStatus status = 5;
  uint32 seat_category = 6;
  string external_product_identifier = 7;
  string external_product_display_name = 8;
}

message ExternalProductSeatActivity {
  string external_product_identifier = 1;
  repeated SeatActionRecord seat_actions = 2;
}

message SeatActionItem {
  SeatObject seat_object = 1;
  SeatState seat_state = 2;
}

message OriginalSeatDate {
  string external_product_identifier = 1;
  google.protobuf.Timestamp created_ts = 2;
}
