"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import sentry_protos.taskworker.v1.taskworker_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class WorkerrServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    PushTask: grpc.UnaryUnaryMultiCallable[
        sentry_protos.taskworker.v1.taskworker_pb2.PushTaskRequest,
        sentry_protos.taskworker.v1.taskworker_pb2.PushTaskResponse,
    ]
    """Receives a task to execute."""

class WorkerrServiceAsyncStub:
    PushTask: grpc.aio.UnaryUnaryMultiCallable[
        sentry_protos.taskworker.v1.taskworker_pb2.PushTaskRequest,
        sentry_protos.taskworker.v1.taskworker_pb2.PushTaskResponse,
    ]
    """Receives a task to execute."""

class WorkerrServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def PushTask(
        self,
        request: sentry_protos.taskworker.v1.taskworker_pb2.PushTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[sentry_protos.taskworker.v1.taskworker_pb2.PushTaskResponse, collections.abc.Awaitable[sentry_protos.taskworker.v1.taskworker_pb2.PushTaskResponse]]:
        """Receives a task to execute."""

def add_WorkerrServiceServicer_to_server(servicer: WorkerrServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
