"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import sentry_protos.taskworker.v1.taskworker_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class WorkerServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    RunTask: grpc.UnaryUnaryMultiCallable[
        sentry_protos.taskworker.v1.taskworker_pb2.RunTaskRequest,
        sentry_protos.taskworker.v1.taskworker_pb2.RunTaskResponse,
    ]
    """Receives a task to execute."""

class WorkerServiceAsyncStub:
    RunTask: grpc.aio.UnaryUnaryMultiCallable[
        sentry_protos.taskworker.v1.taskworker_pb2.RunTaskRequest,
        sentry_protos.taskworker.v1.taskworker_pb2.RunTaskResponse,
    ]
    """Receives a task to execute."""

class WorkerServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def RunTask(
        self,
        request: sentry_protos.taskworker.v1.taskworker_pb2.RunTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[sentry_protos.taskworker.v1.taskworker_pb2.RunTaskResponse, collections.abc.Awaitable[sentry_protos.taskworker.v1.taskworker_pb2.RunTaskResponse]]:
        """Receives a task to execute."""

def add_WorkerServiceServicer_to_server(servicer: WorkerServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
