syntax = "proto3";

package sentry_protos.billing.v1.services.spend_notification.v1;

import "google/protobuf/empty.proto";

// Configuration persisted as JSON by the spend notification data service.
message SpendNotificationConfig {
  uint32 threshold = 1;
  SpendNotificationBudgetType budget_type = 2;

  oneof line_items {
    LineItemUids specific_items = 3;
    google.protobuf.Empty all_items = 4;
  }
}

message SpendNotification {
  uint64 id = 1;
  uint64 organization_id = 2;
  SpendNotificationConfig config = 3;
  bool is_enabled = 4;
}

message LineItemUids {
  repeated string uids = 1;
}

enum SpendNotificationBudgetType {
  SPEND_NOTIFICATION_BUDGET_TYPE_UNSPECIFIED = 0;
  SPEND_NOTIFICATION_BUDGET_TYPE_RESERVED = 1;
  SPEND_NOTIFICATION_BUDGET_TYPE_PAYG = 2;
}
