syntax = "proto3";

package sentry_protos.billing.v1.services.spend_notification.v1;

import "google/protobuf/empty.proto";
import "sentry_protos/billing/v1/services/contract/v1/pricing_config.proto";

// Configuration persisted as JSON by the spend notification data service.
message SpendNotificationConfig {
  uint32 threshold = 1;
  SpendNotificationBudget budget = 2;

  oneof line_items {
    sentry_protos.billing.v1.services.contract.v1.LineItemUids specific_items = 3;
    google.protobuf.Empty all_items = 4;
  }
}

enum SpendNotificationBudget {
  SPEND_NOTIFICATION_BUDGET_UNSPECIFIED = 0;
  SPEND_NOTIFICATION_BUDGET_RESERVED = 1;
  SPEND_NOTIFICATION_BUDGET_PAYG = 2;
}
