[package]
name = "rustgenerator"
version = "0.1.10"
edition = "2021"
publish = false

[dependencies]
glob = "0.3.1"
tonic = "0.12"
tonic-build = "0.12"
prost = "0.13"
prost-build = "0.13"
prost-types = "0.13"
regex = "1.10.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
