name: build

on:
  push:
    branches:
      - release/**

jobs:
  pydist:
    name: python distribution packages
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - run: |
          pip install -r requirements.txt
          make package-py

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: py/dist/*
