name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    name: 'Release a new version'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          fetch-depth: 0

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Generate rust code
        run: |
          make build-rust

      - name: Commit generated rust code
        run: |
          git config user.email bot@getsentry.com
          git config user.name getsentry-bot
          git add rust/src
          git add Cargo.lock
          git commit -m 'regenerate rust bindings'

      - name: Prepare release
        uses: getsentry/action-prepare-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        with:
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
